; A003144: Positions of letter a in the tribonacci word abacabaabacababac... generated by a->ab, b->ac, c->a (cf. A092782).
; Submitted by Soulfly
; 1,3,5,7,8,10,12,14,16,18,20,21,23,25,27,29,31,32,34,36,38,40,42,44,45,47,49,51,52,54,56,58,60,62,64,65,67,69,71,73,75,76,78,80,82,84,86,88,89,91,93,95,97,99,101,102,104,106,108,110,112,113,115,117,119,121,123,125,126,128,130,132,133,135,137,139,141,143,145,146,148,150,152,154,156,157,159,161,163,165,167,169,170,172,174,176,178,180,181,183

mov $2,$0
mul $2,2
lpb $2
  mov $3,$1
  seq $3,92782 ; The ternary tribonacci word; also a Rauzy fractal sequence: fixed point of the morphism 1 -> 12, 2 -> 13, 3 -> 1, starting from a(1) = 1.
  cmp $3,1
  sub $0,$3
  mov $4,$0
  max $4,0
  cmp $4,$0
  add $1,1
  mul $2,$4
  sub $2,1
lpe
mov $0,$1
add $0,1
