; A371896: a(n) is the length of the uninterrupted sequence of primes generated by the polynomial f(x) = x^2 + x + p for x=0,1,..., where p=A001359(n).
; Submitted by Odd-Rod
; 2,4,10,16,2,40,2,2,4,3,2,2,2,3,2,4,2,2,2,3,5,2,2,3,2,2,2,2,5,2,2,3,2,3,3,2,2,2,2,4,2,2,7,2,3,2,5,2,4,4,6,2,2,2,2,2,3,2,2,2,3,2,3,2,2,2,2,3,3,2,2,2,2,2,3,5,2,2,2,2

mov $2,$0
add $2,14
pow $2,2
lpb $2
  sub $2,7
  mov $3,$1
  seq $3,40 ; The prime numbers.
  seq $3,208645 ; Least x>0 such that x^2+x+n is not prime.
  sub $3,1
  mov $5,$3
  neq $3,0
  sub $0,$3
  mov $4,$0
  max $4,0
  equ $4,$0
  add $1,1
  mul $2,$4
lpe
mov $0,$5
add $0,1
