; A371218: Greedy Cantor Dust Partition level 2.
; Submitted by Science United
; 3,6,7,12,15,16,19,30,33,34,39,42,43,46,55
; Formula: a(n) = A354047(A055938(n))+1

mov $1,$0
seq $1,55938 ; Integers not generated by b(n) = b(floor(n/2)) + n (cf. A005187).
seq $1,354047 ; A169683 read as ternary numbers.
mov $0,$1
add $0,1
