; A099238: Square array read by antidiagonals with rows generated by 1/(1-x-x^(k+1)).
; Submitted by STE\/E
; 1,1,2,1,1,4,1,1,2,8,1,1,1,3,16,1,1,1,2,5,32,1,1,1,1,3,8,64,1,1,1,1,2,4,13,128,1,1,1,1,1,3,6,21,256,1,1,1,1,1,2,4,9,34,512,1,1,1,1,1,1,3,5,13,55,1024,1,1,1,1,1,1,2,4,7,19,89,2048

lpb $0
  add $2,1
  sub $0,$2
lpe
mov $1,1
add $2,1
sub $2,$0
lpb $0
  sub $0,$2
  add $3,1
  mov $4,$3
  add $3,$0
  bin $3,$0
  add $1,$3
  mov $3,$4
lpe
mov $0,$1
