; A071024: Triangle read by rows giving successive states of cellular automaton generated by "Rule 92".
; 1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0

lpb $0
  sub $0,2
  mov $2,$0
  add $0,1
  add $3,1
  sub $0,$3
  trn $0,1
lpe
lpb $2
  sub $2,1
  mov $0,$2
  trn $2,9
lpe
mov $1,$0
add $1,1
mod $1,2
