; A071023: Triangle read by rows giving successive states of cellular automaton generated by "Rule 78".
; 1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1

trn $0,1
cal $0,193592 ; Triangle read by rows having n-th row 1, n, n-1, n-2,..., 2, 1 for n>=0.
trn $0,2
add $1,$0
add $1,1
mod $1,2
