; A071023: Triangle read by rows giving successive states of cellular automaton generated by "Rule 78".
; 1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1

sub $0,2
sub $2,$0
max $0,0
cal $0,127739 ; Triangle read by rows, in which row n contains the triangular number T(n) = A000217(n) repeated n times; smallest triangular number greater than or equal to n.
add $2,$0
mov $0,$2
sub $0,1
mov $2,$0
pow $2,2
lpb $2
  mov $1,$2
  mod $2,5
lpe
add $1,1
mod $1,2
