; A071023: Triangle read by rows giving successive states of cellular automaton generated by "Rule 78".
; 1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1

sub $0,2
max $0,0
cal $0,155038 ; Triangle read by rows: T(n,k) is the number of compositions of n with first part k.
sub $0,14
pow $0,2
div $0,3
mov $1,$0
add $1,1
mod $1,2
