; A092180: Permutation of primes generated by triangle shown below.
; Submitted by Jamie Morken(l1)
; 2,3,5,7,11,17,13,19,31,23,37,53,29,41,59,79,43,61,83,109,47,67,89,113,157,71,97,127,163,199,73,101,131,167,211,263,103,137,173,223,269,331,107,139,179,227,271,337,401,149,181,229,277,347,409,479,151,191,233
; Formula: a(n) = A000040(A091995(n)-1)

seq $0,91995 ; Permutation of the natural numbers.
sub $0,1
seq $0,40 ; The prime numbers.
