; A225954: A primitive sequence of order n = 2 generated by f(x) = x^2 - (4*x + 13) over Z/(3*5) (see below).
; Submitted by loader3229
; 1,0,13,7,2,9,2,5,1,9,4,13,14,0,2,8,13,6,13,10,14,6,11,2,1,0,13,7,2,9,2,5,1,9,4,13,14,0,2,8,13,6,13,10,14,6,11,2,1,0,13,7,2,9,2,5,1,9,4,13,14,0,2,8,13,6,13,10,14,6,11,2,1,0,13,7,2,9,2,5

mov $1,1
mov $3,13
mov $4,7
mov $5,2
mov $6,9
mov $7,2
mov $8,5
mov $9,1
mov $10,9
mov $11,4
mov $12,13
mov $13,14
mov $15,2
mov $16,8
mov $17,13
mov $18,6
mov $19,13
mov $20,10
mov $21,14
mov $22,6
mov $23,11
mov $24,2
lpb $0
  rol $1,24
  sub $0,1
lpe
mov $0,$1
