; A114278: A triangle generated by a family of Sierpinski-triangle related polynomials.
; Submitted by Science United
; 1,1,1,1,3,1,1,5,3,1,1,7,7,5,1,1,9,13,15,5,1,1,11,21,35,15,7,1,1,13,31,69,35,27,7,1,1,15,43,121,71,77,29,9,1,1,17,57,195,131,183,91,45,9,1,1,19,73,295,225,385,239,165,45,11,1

lpb $0
  add $1,1
  sub $0,$1
lpe
add $3,$0
add $6,$0
sub $1,$0
add $1,1
lpb $1
  sub $1,1
  mov $4,$3
  bin $4,$1
  mod $4,2
  mov $5,$6
  bin $5,$3
  mul $5,$4
  add $6,1
  add $2,$5
lpe
mov $0,$2
