; A114278: A triangle generated by a family of Sierpinski-triangle related polynomials.
; Submitted by loader3229
; 1,1,1,1,3,1,1,5,3,1,1,7,7,5,1,1,9,13,15,5,1,1,11,21,35,15,7,1,1,13,31,69,35,27,7,1,1,15,43,121,71,77,29,9,1,1,17,57,195,131,183,91,45,9,1,1,19,73,295,225,385,239,165,45,11,1

add $0,1
mov $1,$0
mul $1,8
nrt $1,2
sub $1,1
div $1,2
mov $3,$1
add $3,1
bin $3,2
sub $0,$3
sub $0,1
mov $6,$0
sub $1,$0
add $1,1
lpb $1
  sub $1,1
  mov $4,$0
  bin $4,$1
  mod $4,2
  mov $5,$6
  bin $5,$0
  mul $5,$4
  add $6,1
  add $2,$5
lpe
mov $0,$2
