; A055938: Integers not generated by b(n) = b(floor(n/2)) + n (cf. A005187).
; 2,5,6,9,12,13,14,17,20,21,24,27,28,29,30,33,36,37,40,43,44,45,48,51,52,55,58,59,60,61,62,65,68,69,72,75,76,77,80,83,84,87,90,91,92,93,96,99,100,103,106,107,108,111,114,115,118,121,122,123,124,125,126,129

add $0,1
cal $0,80578
mov $2,$0
mov $3,$2
mov $1,$3
sub $2,2
bin $0,2
sub $2,2
mov $2,$3
lpb $1,2
  mov $4,$0
  add $0,$1
  add $0,2
  mov $1,$2
  mul $3,2
  sub $2,$2
  add $0,$4
  lpb $2,1
    add $4,$2
    mov $6,$0
    mov $4,-2
    mul $6,$1
    mov $0,13
    mul $6,$2
    mul $3,2
    sub $6,$0
    mul $6,$0
    sub $3,1
    lpb $6,1
      add $2,1
      add $6,3
      add $4,1
      sub $6,$6
      add $1,1
      mov $6,2
    lpe
    div $6,13
    mov $6,$3
  lpe
  mov $2,$6
  mov $2,5
  lpb $4,1
    sub $1,$1
    div $4,4
    trn $4,1
    mov $3,$2
    add $0,$4
    mov $2,$5
  lpe
  add $6,60
  mul $6,6
  mov $1,$0
  sub $6,$6
  mov $6,1
  mov $5,$4
  mov $2,$6
  mod $4,10
lpe
mul $5,2
lpb $1,3
  add $5,6
  add $4,2
  div $1,2
  div $4,6
lpe
mov $2,2
mov $1,$3
sub $1,4
add $1,2
