; A071024: Triangle read by rows giving successive states of cellular automaton generated by "Rule 92".
; Submitted by Orange Kid
; 1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0

sub $0,2
lpb $0
  add $2,2
  sub $0,$2
  sub $2,$1
  mov $1,1
lpe
trn $0,2
add $0,1
mod $0,2
