; A071028: Triangle read by rows giving successive states of cellular automaton generated by "Rule 50".
; Submitted by loader3229
; 1,1,0,1,1,0,1,0,1,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0
; Formula: a(n) = -sqrtint(n)-2*truncate((-sqrtint(n)+n+1)/2)+n+1

mov $1,$0
nrt $1,2
sub $0,$1
add $0,1
mod $0,2
