; A071023: Triangle read by rows giving successive states of cellular automaton generated by "Rule 78".
; Submitted by loader3229
; 1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1

add $0,1
mov $2,$0
mul $2,8
nrt $2,2
sub $2,1
div $2,2
mov $1,$2
add $1,1
bin $1,2
mov $3,5
sub $0,$1
sub $0,2
mov $1,$2
sub $1,$0
lpb $0
  bin $0,10
  mov $3,$1
lpe
mov $0,$3
mod $0,2
