; A071022: Triangle read by rows giving successive states of cellular automaton generated by "Rule 70" and by "Rule 198".
; 1,1,1,1,0,1,1,1,0,1,1,0,1,0,1,1,1,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1

lpb $0
  mov $1,$2
  trn $1,$0
  add $2,1
  trn $0,$2
lpe
add $1,1
mov $0,$1
mod $0,2
