; A071030: Triangle read by rows giving successive states of cellular automaton generated by "Rule 54".
; Submitted by Simon Strandgaard
; 1,1,1,1,1,0,0,0,1,1,1,1,0,1,1,1,1,0,0,0,1,0,0,0,1,1,1,1,0,1,1,1,0,1,1,1,1,0,0,0,1,0,0,0,1,0,0,0,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1

mov $2,1
add $2,$0
mov $4,2
lpb $4
  div $4,13
  sub $0,1
  lpb $0
    mov $1,$0
    add $3,1
    add $6,$2
    sub $0,1
    div $1,$3
    add $5,$6
    add $5,$1
  lpe
lpe
mov $0,$5
add $0,1
mod $0,2
