; A071023: Triangle read by rows giving successive states of cellular automaton generated by "Rule 78".
; Submitted by Jamie Morken(w3)
; 1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1

lpb $0
  add $2,1
  sub $0,$2
lpe
mov $3,5
sub $0,1
mov $1,$2
sub $1,$0
lpb $0
  bin $0,10
  mov $3,$1
lpe
mov $0,$3
mod $0,2
