; A071024: Triangle read by rows giving successive states of cellular automaton generated by "Rule 92".
; Submitted by loader3229
; 1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0
; Formula: a(n) = ((-binomial(floor((sqrtint(8*n+24)+1)/2),2)+n+3)==2)-binomial(floor((sqrtint(8*n+24)+1)/2),2)-2*truncate((-binomial(floor((sqrtint(8*n+24)+1)/2),2)+n+3)/2)+n+3

add $0,3
mov $1,$0
mul $1,8
nrt $1,2
add $1,1
div $1,2
bin $1,2
sub $0,$1
mov $1,$0
mod $1,2
equ $0,2
add $0,$1
