; A071023: Triangle read by rows giving successive states of cellular automaton generated by "Rule 78".
; Submitted by Science United
; 1,1,1,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1

lpb $0
  add $2,1
  sub $0,$2
  mov $1,2
  gcd $1,$2
lpe
trn $0,$1
add $0,1
mod $0,2
