; A071022: Triangle read by rows giving successive states of cellular automaton generated by "Rule 70" and by "Rule 198".
; Submitted by Goldislops
; 1,1,1,1,0,1,1,1,0,1,1,0,1,0,1,1,1,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,0

mov $2,$0
mul $2,8
nrt $2,2
add $2,3
div $2,2
bin $2,2
sub $2,$0
mov $1,$2
equ $1,0
mov $3,$2
add $3,$1
mov $0,$3
mod $0,2
