; A071022: Triangle read by rows giving successive states of cellular automaton generated by "Rule 70" and by "Rule 198".
; Submitted by USTL-FIL (Lille Fr)
; 1,1,1,1,0,1,1,1,0,1,1,0,1,0,1,1,1,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,0

lpb $0
  add $1,1
  sub $0,$1
lpe
mov $2,$1
sub $2,$0
add $2,1
mod $2,2
mov $1,$2
pow $1,$0
mov $0,$1
