; A071027: Triangle read by rows giving successive states of cellular automaton generated by "Rule 230".
; Submitted by loader3229
; 1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,1,0,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,1,0,1,1,1,0,1,1,1,1,1,0

add $0,1
mov $2,$0
mul $0,8
nrt $0,2
add $0,1
div $0,2
mov $1,$0
bin $1,2
sub $2,$1
dif $2,$0
mov $1,$0
sub $1,$2
mul $1,$2
add $2,1
bin $2,3
add $0,$1
sub $0,$2
mod $0,2
add $0,2
mod $0,2
