; A071036: Triangle read by rows giving successive states of cellular automaton generated by "Rule 150" when started with a single ON cell.
; Submitted by Arkhenia
; 1,1,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,0,0,0,1,0,0,0,1,1,1,1,0,1,1,1,0,1,1,1,1,0,1,0,0,0,1,0,0,0,1,0,1,1,1,0,1,1,0,1,1,1,0,1,1,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,1

seq $0,84610 ; Triangle, read by rows, where the n-th row lists the (2n+1) coefficients of (1+x-x^2)^n.
mod $0,2
add $0,2
mod $0,2
