; A071028: Triangle read by rows giving successive states of cellular automaton generated by "Rule 50".
; Submitted by omegaintellisys
; 1,1,0,1,1,0,1,0,1,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0

mov $1,$0
nrt $1,2
add $1,$0
mov $0,$1
add $0,3
mod $0,2
