; A071035: Triangle read by rows giving successive states of cellular automaton generated by "Rule 126".
; Submitted by [AF>Le_Pommier>MacBidouille.com]Prof
; 1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,0,1,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1

lpb $0
  add $0,1
  add $1,2
  sub $0,$1
lpe
add $3,$0
div $0,-1
add $0,$1
min $0,$3
mov $2,$1
add $2,1
bin $2,$0
mov $0,$2
mod $0,2
