; A071037: Triangle read by rows giving successive states of cellular automaton generated by "Rule 158".
; Submitted by KetamiNO [YouTube]
; 1,1,1,1,1,1,1,0,1,1,1,1,0,0,1,1,1,1,1,0,1,1,1,0,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,1,0,0,1,1,0,0,1,1,0,0,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0
; Formula: a(n) = (-(n+1)*(truncate(sqrtint(8*floor(n/2))/2)+1)+1)*(-truncate(sqrtint(8*floor(n/2))/2)+floor(n/2)-2)-2*truncate(((-(n+1)*(truncate(sqrtint(8*floor(n/2))/2)+1)+1)*(-truncate(sqrtint(8*floor(n/2))/2)+floor(n/2)-2)-2*truncate(((-(n+1)*(truncate(sqrtint(8*floor(n/2))/2)+1)+1)*(-truncate(sqrtint(8*floor(n/2))/2)+floor(n/2)-2)+1)/2)+3)/2)-2*truncate(((-(n+1)*(truncate(sqrtint(8*floor(n/2))/2)+1)+1)*(-truncate(sqrtint(8*floor(n/2))/2)+floor(n/2)-2)+1)/2)+3

add $0,1
mov $3,$0
sub $0,1
div $0,2
mov $1,$0
mul $1,8
nrt $1,2
div $1,2
mov $2,$1
add $2,1
mul $3,$2
mov $4,1
sub $4,$3
sub $0,1
sub $0,$2
mul $0,$4
add $0,1
mod $0,2
add $0,2
mod $0,2
