; A151819: First component x of pairs (x,y) where x!+y! is a square, sorted on x.
; 0,0,0,1,1,1,2,4,4,4

add $0,1
seq $0,191106 ; Increasing sequence generated by these rules: a(1)=1, and if x is in a then 3x-2 and 3x are in a.
sub $0,1
add $1,$0
mod $1,3
add $1,$0
div $1,2
sub $1,2
div $1,6
