; A126258: Triangle generated by Pascal's rule with left diagonal = [1,0,2,0,3,0,4,...] (A000027 with interpolated zeros) and right diagonal = [1,1,1,1,1,...].
; Submitted by loader3229
; 1,0,1,2,1,1,0,3,2,1,3,3,5,3,1,0,6,8,8,4,1,4,6,14,16,12,5,1,0,10,20,30,28,17,6,1,5,10,30,50,58,45,23,7,1,0,15,40,80,108,103,68,30,8,1,6,15,55,120,188,211,171,98,38,9,1,0,21,70,175,308,399,382,269,136,47,10,1

add $0,1
mov $2,$0
mul $2,8
nrt $2,2
sub $2,1
div $2,2
mov $6,$2
add $6,1
bin $6,2
sub $0,$6
sub $0,1
add $2,2
sub $2,$0
mov $3,$0
mov $4,$0
mov $0,$2
lpb $0
  sub $0,2
  add $5,1
  sub $3,1
  add $3,$0
  bin $3,$0
  mul $3,$5
  add $1,$3
  mov $3,$4
lpe
mov $0,$1
