; A261654: Lead almost-Pythagorean triples generated by primitive Pythagorean triples of the form (2i-1, 2i^2-2i, 2i^2-2i+1), i >= 2.
; Submitted by loader3229
; 4,7,8,6,17,18,8,31,32,10,49,50,12,71,72,14,97,98,16,127,128,18,161,162,20,199,200,22,241,242,24,287,288,26,337,338,28,391,392,30,449,450,32,511,512,34,577,578
; Formula: a(n) = truncate((min(n-1,(n-1)%3)*(min(n-1,(n-1)%3)*d(n-1)+c(n-1))+b(n-1)-8)/2)+4, b(n) = 6*d(n-3)+2*c(n-3)+b(n-3), b(8) = 16, b(7) = 16, b(6) = 16, b(5) = 12, b(4) = 12, b(3) = 12, b(2) = 8, b(1) = 8, b(0) = 8, c(n) = 3*b(n-3)+c(n-3), c(8) = 68, c(7) = 68, c(6) = 68, c(5) = 32, c(4) = 32, c(3) = 32, c(2) = 8, c(1) = 8, c(0) = 8, d(n) = -b(n-3)+d(n-3), d(8) = -22, d(7) = -22, d(6) = -22, d(5) = -10, d(4) = -10, d(3) = -10, d(2) = -2, d(1) = -2, d(0) = -2

#offset 1

mov $1,8
mov $2,8
mov $3,-2
sub $0,1
lpb $0
  sub $0,3
  mov $4,$1
  mul $4,3
  mov $6,$3
  mul $6,6
  mov $7,$1
  mul $7,-1
  mov $5,$2
  mul $5,2
  add $2,$4
  add $3,$7
  add $1,$6
  add $1,$5
lpe
mul $3,$0
add $2,$3
mul $0,$2
add $0,$1
sub $0,8
div $0,2
add $0,4
