; A261654: Lead almost-Pythagorean triples generated by primitive Pythagorean triples of the form (2i-1, 2i^2-2i, 2i^2-2i+1), i >= 2.
; Submitted by loader3229
; 4,7,8,6,17,18,8,31,32,10,49,50,12,71,72,14,97,98,16,127,128,18,161,162,20,199,200,22,241,242,24,287,288,26,337,338,28,391,392,30,449,450,32,511,512,34,577,578

#offset 1

mov $1,4
mov $2,7
mov $3,8
mov $4,6
mov $5,17
mov $6,18
mov $7,8
mov $8,31
mov $9,32
sub $0,1
lpb $0
  rol $1,9
  mov $10,$3
  mul $10,-3
  add $9,$10
  mov $10,$6
  mul $10,3
  sub $0,1
  add $9,$10
lpe
mov $0,$1
