; A261654: Lead almost-Pythagorean triples generated by primitive Pythagorean triples of the form (2i-1, 2i^2-2i, 2i^2-2i+1), i >= 2.
; Submitted by [AF>Libristes] Dudumomo
; 4,7,8,6,17,18,8,31,32,10,49,50,12,71,72,14,97,98,16,127,128,18,161,162,20,199,200,22,241,242,24,287,288,26,337,338,28,391,392,30,449,450,32,511,512,34,577,578

#offset 1

sub $0,1
lpb $0
  add $1,1
  sub $0,$1
  equ $1,1
  add $2,1
lpe
mul $1,$2
add $2,3
sub $2,$0
add $0,1
add $1,$0
add $1,1
mul $2,$1
add $2,$1
mov $0,$2
div $0,2
