; A125047: Infinite word generated by mapping 1->12, 2->13, 3->43, 4->42 starting at 1.
; Submitted by Christian Krause
; 1,2,1,3,1,2,4,3,1,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,4,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,1,2,1,3,4,2,4,3,4,2,1,3,1,2,4,3,4,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,1,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,4,2,1,3,4,2,4,3,4,2,1,3

mov $2,$0
seq $0,38189 ; Bit to left of least significant 1-bit in binary expansion of n.
add $0,5
div $0,2
add $2,$0
mod $2,2
add $2,$0
add $0,$2
sub $0,3
