; A125047: Infinite word generated by mapping 1->12, 2->13, 3->43, 4->42 starting at 1.
; Submitted by shiva
; 1,2,1,3,1,2,4,3,1,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,4,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,1,2,1,3,4,2,4,3,4,2,1,3,1,2,4,3,4,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,1,2,1,3,4,2,4,3
; Formula: a(n) = (floor(if((n-1)==0,0,(n-1)/(2^valuation(n-1,2)))/2)%2+n+11)%2+2*(floor(if((n-1)==0,0,(n-1)/(2^valuation(n-1,2)))/2)%2)+1

#offset 1

sub $0,1
mov $1,$0
dir $0,2
div $0,2
mod $0,2
add $0,12
add $1,$0
mod $1,2
add $1,$0
add $0,$1
sub $0,23
