; A125047: Infinite word generated by mapping 1->12, 2->13, 3->43, 4->42 starting at 1.
; Submitted by Cruncher Pete
; 1,2,1,3,1,2,4,3,1,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,4,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,1,2,1,3,4,2,4,3,4,2,1,3,1,2,4,3,4,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,1,2,1,3,4,2,4,3,1,2,1,3,1,2,4,3,4,2,1,3,4,2,4,3,4,2,1,3
; Formula: a(n) = ((A038189(n)+n+12)%2+2*A038189(n)+24)-23

mov $1,$0
seq $0,38189 ; Bit to left of least significant 1-bit in binary expansion of n.
add $0,12
add $1,$0
mod $1,2
add $1,$0
add $0,$1
sub $0,23
