; A064279: Number of ordered pairs a,b of elements in the cyclic group C_n such that the subgroup generated by the pair a,b is a proper subgroup of C_n.
; Submitted by Simon Strandgaard
; 0,1,1,4,1,12,1,16,9,28,1,48,1,52,33,64,1,108,1,112,57,124,1,192,25,172,81,208,1,324,1,256,129,292,73,432,1,364,177,448,1,612,1,496,297,532,1,768,49,700,297,688,1,972,145,832,369,844,1,1296,1,964,513,1024
; Formula: a(n) = (n+1)^2-A063659((n+1)^2-1)

add $0,1
pow $0,2
sub $0,1
mov $1,$0
seq $1,63659 ; The number of integers m in [1..n] for which gcd(m,n) is not divisible by a square greater than 1.
sub $0,$1
add $0,1
