; A110266: Number of blocks of ON cells in n-th row of triangle generated by Wolfram's "Rule 30".
; Submitted by Science United
; 1,1,2,2,3,3,4,3,4,5,6,6,7,7,8,7,7,8,10,9,9,11,14,12,11,12,15,16,14,15,17,14,15,17,20,18,18,18,21,21,17,19,21,20,23,22,23,22,23,21,27,30,26,27,29,29,28,28,33,31,30,31,36,32,28,29,33,33,33,35,38,31,28,37,38,40,43,42,44,42

#offset 1

sub $0,2
mov $1,1
mov $4,$0
add $4,1
lpb $4
  sub $4,1
  mov $2,$1
  mul $2,2
  bxo $2,$1
  add $1,$2
  bxo $1,$2
lpe
mov $3,$1
div $3,2
mov $0,$1
bxo $0,$3
dgs $0,2
div $0,2
add $0,1
