; A110266: Number of blocks of ON cells in n-th row of triangle generated by Wolfram's "Rule 30".
; Submitted by [SG-FC] hl
; 1,1,2,2,3,3,4,3,4,5,6,6,7,7,8,7,7,8,10,9,9,11,14,12,11,12,15,16,14,15,17,14,15,17,20,18,18,18,21,21,17,19,21,20,23,22,23,22,23,21,27,30,26,27,29,29,28,28,33,31,30,31,36,32,28,29,33,33,33,35,38,31,28,37,38,40,43,42,44,42,35,39,44,47,47,42,46,41,36,40,51,45,43,44,48,48,47,47,58,57

seq $0,110240 ; Decimal form of binary integer produced by the ON cells at n-th generation following Wolfram's Rule 30 cellular automaton starting from a single ON-cell represented as 1.
seq $0,5811 ; Number of runs in binary expansion of n (n>0); number of 1's in Gray code for n.
div $0,2
add $0,1
