; A157452: Number generated by regarding the numbers in row n of A003983 as digits of a base n number.
; Submitted by Cruncher Pete
; 1,3,16,105,961,11137,160000,2738385,54479161,1234554321,31384248336,884241045961,27342890695849,920521266133785,33512287502995456,1311768467139281697,54933923639963082961,2450641333396432006369

add $0,1
mov $2,$0
lpb $0
  add $4,1
  min $0,$4
  mov $3,$0
  add $3,$0
  mul $1,$2
  add $1,$3
  mov $0,$2
  sub $0,$4
lpe
mov $0,$1
sub $0,2
div $0,2
add $0,1
