; A157451: Number generated by regarding the numbers in row n of A139038 as digits of a base n number.
; Submitted by Vato
; 1,3,13,85,806,9583,140050,2434185,49031983,1122332211,28768909071,816222524845,25389827448220,859153189293015,31417769545499716,1234605616147931665,51882038993710230701,2321660210597147557819

add $0,1
mov $2,$0
lpb $0
  add $4,1
  min $0,$4
  add $0,1
  cmp $3,0
  add $3,$0
  div $3,2
  mul $1,$2
  add $1,$3
  mov $0,$2
  sub $0,$4
lpe
mov $0,$1
