; A128941: Cardinality of the free modular lattice generated by two elements and a chain of length n.
; Submitted by Jamie Morken(w1)
; 4,28,138,629,2784,12134,52366,224404,956514,4060036,17175130,72454073,304941384,1280898302,5371301502,22491017756,94055344242,392888085098,1639534704630,6835739258996,28477594607346,118551827347574

add $0,3
sub $1,$0
mov $4,$0
mul $4,2
lpb $0
  sub $0,1
  mov $3,$4
  bin $3,$1
  add $3,$2
  add $1,2
  add $2,$3
lpe
mov $0,$2
sub $0,2
