; A362556: Number of distinct n-digit suffixes generated by iteratively multiplying an integer by 8, where the initial integer is 1.
; Submitted by Penguin
; 5,21,101,502,2502,12502,62503,312503,1562503,7812504,39062504,195312504,976562505,4882812505,24414062505,122070312506,610351562506,3051757812506,15258789062507,76293945312507,381469726562507
; Formula: a(n) = n/3+4*5^n+1

mov $1,5
pow $1,$0
mul $1,4
div $0,3
add $0,$1
add $0,1
