; A362882: Number of even numbers generated by adding two distinct odd primes <= prime(n+1).
; Submitted by Wood
; 0,1,3,6,8,11,14,17,20,25,28,33,37,40,44,47,53,57,62,66,70,75,79,85,89,93,98,102,106,113,117,122,129,134,140,145,150,157,161,166,172,176,181,186,191,196,202,210,214,221,225,230,236,241,245,248,256,264

#offset 1

sub $0,1
lpb $0
  sub $0,1
  mov $3,$0
  max $3,0
  add $3,3
  mov $2,$3
  seq $2,40 ; The prime numbers.
  div $2,2
  mov $3,$2
  mul $3,2
  add $3,1
  seq $3,83059 ; a(n) is the number of natural numbers k such that A078496(k)=n.
  add $3,1
  sub $1,1
  add $1,$3
lpe
mov $0,$1
