; A362882: Number of even numbers generated by adding two distinct odd primes <= prime(n+1).
; Submitted by Science United
; 0,1,3,6,8,11,14,17,20,25,28,33,37,40,44,47,53,57,62,66,70,75,79,85,89,93,98,102,106,113,117,122,129,134,140,145,150,157,161,166,172,176,181,186,191,196,202,210,214,221,225,230,236,241,245,248,256,264
; Formula: a(n) = -n+A049880(n)-1

mov $1,$0
seq $0,49880 ; a(n) is the number of distinct sums of 2 different primes chosen from the first n primes.
sub $0,1
sub $0,$1
