; A069763: Frobenius number of the numerical semigroup generated by consecutive cubes.
; Submitted by loader3229
; 181,1637,7811,26659,73529,174761,372007,727271,1328669,2296909,3792491,6023627,9254881,13816529,20114639,28641871,39988997,54857141,74070739,98591219,129531401,168170617,215970551,274591799,345911149
; Formula: a(n) = n*(n*(n*(n*(n*(n+3)+3)-1)-3)-3)-1

#offset 2

mov $1,$0
add $0,3
mul $0,$1
add $0,3
mul $0,$1
sub $0,1
mul $0,$1
sub $0,3
mul $0,$1
sub $0,3
mul $0,$1
sub $0,1
