; A069760: Frobenius number of the numerical semigroup generated by consecutive centered square numbers.
; 47,287,959,2399,5039,9407,16127,25919,39599,58079,82367,113567,152879,201599,261119,332927,418607,519839,638399,776159,935087,1117247,1324799,1559999,1825199,2122847
; Formula: a(n) = (2*(n+2)^2-1)^2-2

add $0,2
pow $0,2
mul $0,2
sub $0,1
pow $0,2
sub $0,2
