; A069660: Order of the subgroup of the symmetric group S_n generated by the cycles (1,3) and (1,2,3,...,n).
; Submitted by Dark Angel
; 6,8,120,72,5040,1152,362880,28800,39916800,1036800,6227020800,50803200,1307674368000,3251404800,355687428096000,263363788800,121645100408832000,26336378880000,51090942171709440000

add $0,1
mov $1,1
mov $2,$0
lpb $0
  mov $3,$2
  gcd $3,2
  mov $4,$0
  add $4,1
  div $4,$3
  sub $0,1
  mov $3,$4
  mul $3,$1
  add $1,$3
lpe
mov $0,$1
mul $0,2
