; A069763: Frobenius number of the numerical semigroup generated by consecutive cubes.
; Submitted by USTL-FIL (Lille Fr)
; 181,1637,7811,26659,73529,174761,372007,727271,1328669,2296909,3792491,6023627,9254881,13816529,20114639,28641871,39988997,54857141,74070739,98591219,129531401,168170617,215970551,274591799,345911149
; Formula: a(n) = ((n+2)^3-1)*((n+3)^3-1)-1, a(2) = 7811, a(1) = 1637, a(0) = 181

mov $3,1
add $0,2
lpb $0
  sub $0,1
  mov $2,$1
  mov $1,$3
  add $1,1
  pow $1,3
  sub $1,1
  mul $2,$1
  sub $2,1
  add $3,1
lpe
mov $0,$2
