; A127243: Triangle whose k-th column is generated by (1+A010060(1+k)x)*x^k.
; 1,1,1,0,1,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

cal $0,128229 ; A natural number transform, inverse of signed A094587.
cal $0,50292 ; a(2n) = 2n - a(n), a(2n+1) = 2n + 1 - a(n) (for n >= 0).
mov $1,$0
mod $1,2
