; A090298: Permutation of natural numbers generated by 5-row array shown below.
; Submitted by loader3229
; 1,9,2,11,8,3,19,12,7,4,21,18,13,6,5,29,22,17,14,10,31,28,23,16,15,39,32,27,24,20,41,38,33,26,25,49,42,37,34,30,51,48,43,36,35,59,52,47,44,40,61,58,53,46,45,69,62,57,54,50,71,68,63,56,55,79,72,67,64,60,81,78

#offset 1

mov $1,1
mov $2,9
mov $3,2
mov $4,11
mov $5,8
mov $6,3
mov $7,19
mov $8,12
mov $9,7
mov $10,4
mov $11,21
mov $12,18
mov $13,13
mov $14,6
mov $15,5
mov $16,29
mov $17,22
mov $18,17
mov $19,14
mov $20,10
sub $0,1
lpb $0
  mov $1,0
  rol $1,20
  sub $20,$10
  add $20,$11
  add $20,$11
  sub $20,$12
  sub $20,$12
  add $20,$13
  add $20,$13
  sub $20,$14
  sub $20,$14
  add $20,$15
  add $20,$15
  sub $20,$16
  sub $20,$16
  add $20,$17
  add $20,$17
  sub $20,$18
  sub $20,$18
  add $20,$19
  add $20,$19
  sub $0,1
lpe
mov $0,$1
