; A090243: Permutation of natural numbers generated by 4-rowed array shown below.
; Submitted by loader3229
; 1,7,2,11,6,3,13,10,5,4,19,14,9,8,23,18,15,12,25,22,17,16,31,26,21,20,35,30,27,24,37,34,29,28,43,38,33,32,47,42,39,36,49,46,41,40,55,50,45,44,59,54,51,48,61,58,53,52,67,62,57,56,71,66,63,60,73,70,65,64,79,74

#offset 1

mov $1,1
mov $2,7
mov $3,2
mov $4,11
mov $5,6
mov $6,3
mov $7,13
mov $8,10
mov $9,5
mov $10,4
mov $11,19
mov $12,14
mov $13,9
mov $14,8
mov $15,23
mov $16,18
mov $17,15
mov $18,12
mov $19,25
sub $0,1
lpb $0
  sub $0,1
  mul $1,0
  mov $20,$1
  mov $1,$2
  mov $2,$3
  mov $3,$4
  mov $4,$5
  mov $5,$6
  mov $6,$7
  mul $7,-1
  add $20,$7
  add $20,$8
  add $20,$19
  mov $7,$8
  mov $8,$9
  mov $9,$10
  mov $10,$11
  mov $11,$12
  mov $12,$13
  mov $13,$14
  mov $14,$15
  mov $15,$16
  mov $16,$17
  mov $17,$18
  mov $18,$19
  mov $19,$20
lpe
mov $0,$1
