; A047992: Number of distinct permutations generated by shuffling n cards with "clump size" <= 2.
; Submitted by Simon Strandgaard
; 2,5,10,16,26,42,68,110,178,288,466,754,1220,1974,3194,5168,8362,13530,21892,35422,57314,92736,150050,242786,392836,635622,1028458,1664080,2692538,4356618,7049156,11405774,18454930,29860704,48315634,78176338,126491972
; Formula: a(n) = -(8/(b(n)+c(n)))+b(n)+c(n), b(n) = b(n-1)+d(n-1), b(2) = 5, b(1) = 3, b(0) = 2, c(n) = b(n-1)+d(n-1), c(2) = 5, c(1) = 3, c(0) = 2, d(n) = b(n-2)+d(n-2), d(2) = 3, d(1) = 2, d(0) = 1

mov $3,1
mov $4,1
add $0,2
lpb $0
  sub $0,1
  add $2,$4
  mov $4,$3
  mov $3,$2
lpe
add $3,$2
mov $1,8
div $1,$3
mov $0,$3
sub $0,$1
