; A047992: Number of distinct permutations generated by shuffling n cards with "clump size" <= 2.
; Submitted by loader3229
; 2,5,10,16,26,42,68,110,178,288,466,754,1220,1974,3194,5168,8362,13530,21892,35422,57314,92736,150050,242786,392836,635622,1028458,1664080,2692538,4356618,7049156,11405774,18454930,29860704,48315634,78176338,126491972
; Formula: a(n) = a(n-1)+a(n-2)+binomial(-a(n-3)+a(n-2)+2,a(n-2)), a(3) = 5, a(2) = 2, a(1) = 1, a(0) = 1

#offset 2

mov $3,1
lpb $0
  sub $0,1
  bin $1,$3
  add $3,$2
  add $1,$3
  sub $2,$1
  add $1,$2
  add $1,2
  mul $2,-1
lpe
mov $0,$3
