; A183124: Magnetic Tower of Hanoi, number of moves of disk number n, generated by a certain algorithm, yielding a "forward moving" non-optimal solution of the [NEUTRAL ; NEUTRAL ; NEUTRAL] pre-colored puzzle.
; Submitted by Science United
; 0,1,3,7,19,53,153,451,1339,4001,11981,35919,107727,323149,969409,2908187,8724515,26173497,78520437,235561255,706683703

mov $2,1
mov $3,4
mov $4,11
mov $5,30
mov $6,83
mov $7,236
mov $8,687
mov $9,2026
lpb $0
  mul $1,0
  rol $1,9
  add $1,$11
  mov $10,$4
  mul $10,-3
  add $9,$10
  mov $10,$5
  mul $10,7
  add $9,$10
  sub $9,$6
  sub $9,$6
  mov $10,$7
  mul $10,-6
  sub $11,$1
  add $9,$10
  mov $10,$8
  mul $10,5
  sub $0,1
  add $9,$10
lpe
mov $0,$1
