; A183213: Ordering of the numbers in the set S generated by these rules:  1 is in S, and if n is in S, then floor[(3n-1)/2] and 3n are in S.
; Submitted by Tae Hyun Kim
; 1,3,4,5,7,9,10,12,13,14,15,17,19,20,21,22,25,27,28,29,30,31,32,36,37,39,40,41,42,43,44,45,46,47,51,53,55,57,58,59,60,61,62,63,64,65,66,67,68,70,75,76,79,81,82,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,100,101,104,108,111,112,113,117,118,120,121,122,123,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141

mov $4,1
mov $2,$0
add $2,2
pow $2,4
lpb $2
  mov $3,$1
  seq $3,117943 ; a(1) = 0, a(2) = 1; a(3n) = a(n); if every third term (a(3), a(6), a(9), ...) is deleted, this gives back the original sequence.
  add $3,$4
  div $3,2
  gcd $3,2
  sub $0,$3
  add $0,1
  add $1,$4
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  sub $2,1
lpe
mov $0,$1
add $0,1
