; A183543: Second of two complementary trees generated by the Wythoff sequences.
; Submitted by [AF] Kalianthys
; 3,6,11,10,18,19,32,17,29,30,50,31,52,53,87,28,47,48,79,49,81,82,134,51,84,85,139,86,141,142,231,46,76,77,126,78,128,129,210,80,131,132,215,133,217,218,354,83,136,137,223,138,225,226,367,140,228,229,372,230,374,375,608

seq $0,4755 ; Binary expansion starts 11.
seq $0,48680 ; Nonnegative integers A001477 expanded with rewrite 0->0, 01->1, then interpreted as Zeckendorffian expansions (as numbers of Fibonacci number system).
sub $0,1
