; A183123: Magnetic Tower of Hanoi, total number of moves, generated by a certain algorithm, yielding a "forward moving" non-optimal solution of the [NEUTRAL ; NEUTRAL ; NEUTRAL] pre-colored puzzle.
; Submitted by Simon Strandgaard
; 0,1,4,11,30,83,236,691,2050,6123,18336,54971,164870,494563,1483636,4450851,13352490,40057403,120172136,360516331,1081548910,3244646643,9733939836,29201819411,87605458130,262816374283,788449122736,2365347368091,7096042104150

lpb $0
  sub $0,1
  sub $1,$2
  max $2,1
  mul $3,2
  add $4,$2
  add $5,2
  add $2,$3
  add $2,$5
  sub $3,$1
  mod $1,2
  min $5,4
lpe
mov $0,$4
