; A183120: Magnetic Tower of Hanoi, number of moves of disk number k, generated by a certain algorithm, yielding a "forward moving" non-optimal solution of the [RED ; NEUTRAL ; NEUTRAL] or [NEUTRAL ; NEUTRAL ; BLUE] pre-colored puzzle.
; Submitted by Simon Strandgaard
; 0,1,3,7,19,55,159,471,1403,4199,12583,37735,113187,339543,1018607,3055799,9167371,27502087,82506231,247518663,742555955,2227667831,6683003455,20049010327,60147030939,180441092775,541323278279,1623969834791,4871909504323

lpb $0
  sub $0,1
  sub $1,$2
  max $2,1
  mul $3,2
  mov $4,$2
  add $5,2
  add $2,$3
  add $2,$5
  sub $3,$1
  mod $1,2
lpe
mov $0,$4
