; A287312: Primes that can be generated by the concatenation in base 9, in ascending order, of two consecutive integers read in base 10.
; Submitted by [AF>Amis des Lapins] Jean-Luc
; 11,31,41,61,71,739,821,1231,1559,1723,2297,2543,2707,2789,2953,3527,3691,4019,5003,5167,5413,5659,5741,5987,6151,6397,65701,66431,67891,72271,76651,81031,81761,83221,85411,100741,102931,108041,121181,135781,136511,140891

mov $2,$0
add $2,2
pow $2,2
lpb $2
  sub $2,1
  mov $3,$1
  seq $3,20337 ; Numbers whose base-9 representation is the juxtaposition of two identical strings.
  mov $5,$3
  seq $3,1222 ; Number of prime divisors of n counted with multiplicity (also called big omega of n, bigomega(n) or Omega(n)).
  cmp $3,1
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
lpe
mov $0,$5
add $0,1
