; A287308: Primes that can be generated by the concatenation in base 7, in ascending order, of two consecutive integers read in base 10.
; Submitted by Science United
; 17,41,401,601,701,751,1051,1151,1201,1301,1451,1601,1801,1901,1951,2251,2351,18233,19609,20297,20641,21673,25457,25801,26489,26833,31649,33713,34057,35089,36809,38873,39217,41281,41969,46441,47129,49193,49537,51257,52289

mov $2,$0
add $2,2
pow $2,2
lpb $2
  mov $3,$1
  seq $3,20335 ; Numbers whose base-7 representation is the juxtaposition of two identical strings.
  mov $5,$3
  mul $5,2
  seq $3,10051 ; Characteristic function of primes: 1 if n is prime, else 0.
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  trn $2,1
lpe
mov $0,$5
sub $0,32
div $0,2
add $0,17
