; A287302: Primes that can be generated by the concatenation in base 4, in ascending order, of two consecutive integers read in base 10.
; Submitted by USTL-FIL (Lille Fr)
; 11,103,137,239,1171,1301,1951,2081,2341,2731,2861,3121,3251,3511,16963,17477,20047,21589,23131,26729,30841,34439,40093,43177,43691,45233,46261,60139,61681,63737,270601,272651,278801,291101,295201,297251,315701,321851,325951

mov $2,$0
add $2,2
pow $2,2
lpb $2
  mov $3,$1
  seq $3,20332 ; Numbers whose base-4 representation is the juxtaposition of two identical strings.
  mov $5,$3
  seq $3,10051 ; Characteristic function of primes: 1 if n is prime, else 0.
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  trn $2,1
lpe
mov $0,$5
add $0,1
