; A287300: Primes that can be generated by the concatenation in base 3, in ascending order, of two consecutive integers read in base 10.
; Submitted by USTL-FIL (Lille Fr)
; 5,31,41,61,71,281,337,421,449,617,673,701,2297,2543,2707,2789,2953,3527,3691,4019,5003,5167,5413,5659,5741,5987,6151,6397,21961,22937,23669,24889,25621,26597,27329,27817,28549,28793,30013,31477,31721,32941,34649,35381

mov $2,$0
add $2,2
pow $2,2
lpb $2
  mov $3,$1
  seq $3,20331 ; Numbers whose base-3 representation is the juxtaposition of two identical strings.
  mov $5,$3
  seq $3,10051 ; Characteristic function of primes: 1 if n is prime, else 0.
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  trn $2,1
lpe
mov $0,$5
add $0,1
