; A287018: Primes that can be generated by the concatenation in base 2, in ascending order, of two consecutive integers read in base 10.
; Submitted by damotbe
; 11,37,137,239,661,727,859,991,2081,2341,2731,2861,3121,3251,3511,9547,10321,10837,11353,13159,13417,13933,14449,15739,34439,40093,43177,43691,45233,46261,60139,61681,63737,135433,138511,139537,144667,146719,151849,154927

mov $2,$0
add $2,2
pow $2,2
lpb $2
  mov $3,$1
  seq $3,87737 ; Value of (n,n+1) concatenated in binary representation.
  mov $5,$3
  sub $3,1
  seq $3,10051 ; Characteristic function of primes: 1 if n is prime, else 0.
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  trn $2,1
lpe
mov $0,$5
