; A287304: Primes that can be generated by the concatenation in base 5, in ascending order, of two consecutive integers read in base 10.
; Submitted by BlackOps13
; 7,13,19,131,157,313,443,521,547,599,3529,3907,4159,4663,4789,5167,5419,5923,6301,6427,6553,6679,7057,7309,7561,7687,8191,8317,8443,8821,9199,9829,10333,10459,10711,10837,11467,11593,11719,11971,12097,12601,12853,12979

mov $2,$0
add $2,2
pow $2,2
lpb $2
  mov $3,$1
  seq $3,20333 ; Numbers whose base-5 representation is the juxtaposition of two identical strings.
  mov $5,$3
  seq $3,10051 ; Characteristic function of primes: 1 if n is prime, else 0.
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  trn $2,1
lpe
mov $0,$5
add $0,1
