; A287306: Primes that can be generated by the concatenation in base 6, in ascending order, of two consecutive integers read in base 10.
; Submitted by Fardringle
; 29,223,593,1259,8681,11719,14323,16493,16927,18229,19531,20399,21701,23003,26041,28211,29947,31249,32117,34721,36457,39929,41231,42533,42967,44269,45137,46439,293123,316469,324251,350191,355379,363161,381319,396883,402071,425417

mov $2,$0
add $2,3
pow $2,2
lpb $2
  mov $3,$1
  seq $3,20334 ; Numbers whose base-6 representation is the juxtaposition of two identical strings.
  mov $5,$3
  seq $3,10051 ; Characteristic function of primes: 1 if n is prime, else 0.
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  trn $2,1
lpe
mov $0,$5
add $0,1
