; A097251: Numbers whose set of base 5 digits is {0,4}.
; 0,4,20,24,100,104,120,124,500,504,520,524,600,604,620,624,2500,2504,2520,2524,2600,2604,2620,2624,3000,3004,3020,3024,3100,3104,3120,3124,12500,12504,12520,12524,12600,12604,12620,12624,13000,13004,13020

cal $0,191107 ; Increasing sequence generated by these rules:  a(1)=1, and if x is in a then 3x-2 and 3x+1 are in a.
cal $0,37453 ; Positive numbers n such that the base 5 representation of n contains no 3 or 4.
mov $1,$0
div $1,5
mul $1,4
