; A063808: Spherical growth series for Z as generated by {2, 3}.
; Submitted by loader3229
; 1,4,8,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
; Formula: a(n) = floor(sumdigits(min(n,3)*(min(n,3)+1)*(min(n,3)+2)*(min(n,3)+3),65)/8)+1

min $0,3
fac $0,4
dgs $0,65
div $0,8
add $0,1
