; A063808: Spherical growth series for Z as generated by {2, 3}.
; Submitted by Skillz
; 1,4,8,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
; Formula: a(n) = (floor(binomial(9,2*n+3)/15)+6)%10

mul $0,2
add $0,3
mov $1,9
bin $1,$0
mov $0,$1
div $0,15
add $0,6
mod $0,10
