; A217990: Size of largest semigroup generated by one Boolean n X n matrix.
; Submitted by Simon Strandgaard
; 1,2,5,10,17,26,37,50,65,82,101,122,145,170,197,226,257,290,420
; Formula: a(n) = max(A113025(A056536(n)-1),n^2+1)

mov $1,$0
pow $1,2
add $1,1
seq $0,56536 ; Mapping from half-antidiagonal reading of the triangle (as used in A028297) to the column-by-column reading of the triangular tables.
sub $0,1
seq $0,113025 ; Triangle of integer coefficients of polynomials P(n,x) of degree n, and falling powers of x, arising in diagonal Padé approximation of exp(x).
max $0,$1
