; A217990: Size of largest semigroup generated by one Boolean n X n matrix.
; Submitted by Simon Strandgaard
; 1,2,5,10,17,26,37,50,65,82,101,122,145,170,197,226,257,290,420

mov $1,$0
pow $1,2
add $1,1
seq $0,59344 ; Triangle read by rows: row n consists of the nonzero coefficients of the expansion of 2^n x^n in terms of Hermite polynomials with decreasing subscripts.
max $0,$1
