; A217990: Size of largest semigroup generated by one Boolean n X n matrix.
; Submitted by Simon Strandgaard
; 1,2,5,10,17,26,37,50,65,82,101,122,145,170,197,226,257,290,420

#offset 1

sub $0,1
mov $1,$0
pow $1,2
add $1,1
add $0,1
mov $3,$0
mul $0,4
sub $0,3
nrt $0,2
mov $2,$0
pow $2,2
div $2,4
sub $3,$2
mov $2,$3
mov $3,$0
sub $3,$2
bin $3,2
add $3,$0
mov $5,$3
mul $5,8
nrt $5,2
sub $5,1
div $5,2
mov $6,$5
add $6,1
bin $6,2
mov $0,$3
sub $0,$6
sub $0,1
add $5,$0
mov $4,$5
bin $4,$0
sub $5,$0
lpb $0
  sub $0,1
  mul $4,$5
  sub $5,1
lpe
mov $0,$4
max $0,$1
