; A159294: Number of ways that a 1 X n rectangular tile T, marked into n unit squares, can be surrounded by one layer of copies of itself laid in the plane grid generated by the units of T. Ways that differ by rotation or reflection are not counted as different. The surrounded tile is the exact surrounded region.
; Submitted by loader3229
; 1,153,301,517,825,1234,1774,2454,3310,4351,5619,7123,8911,10992,13420,16204,19404,23029,27145,31761,36949,42718,49146,56242,64090,72699,82159,92479,103755,115996,129304,143688,159256,176017,194085,213469,234289,256554,280390,305806,332934,361783,392491,425067,459655,496264,535044,576004,619300,664941,713089,763753,817101,873142,932050,993834,1058674,1126579,1197735,1272151,1350019,1431348,1516336,1604992,1697520,1793929,1894429,1999029,2107945,2221186,2338974,2461318,2588446,2720367,2857315

#offset 1

mov $1,1
mov $2,153
mov $3,301
mov $4,517
mov $5,825
mov $6,1234
mov $7,1774
mov $8,2454
sub $0,1
lpb $0
  mul $1,0
  rol $1,8
  mov $9,$2
  mul $9,-3
  add $8,$1
  add $8,$9
  add $8,$3
  mov $9,$4
  mul $9,5
  add $8,$9
  mov $9,$5
  mul $9,-5
  add $8,$9
  sub $8,$6
  mov $9,$7
  mul $9,3
  sub $0,1
  add $8,$9
lpe
mov $0,$1
