; A320342: Maximum term in Cunningham chain of the first kind generated by the n-th prime.
; Submitted by [TA]crashtech
; 47,7,47,7,47,13,17,19,47,59,31,37,167,43,47,107,59,61,67,71,73,79,167,2879,97,101,103,107,109,227,127,263,137,139,149,151,157,163,167,347,2879,181,383,193,197,199,211,223,227,229,467,479,241,503,257,263,269,271,277,563,283,587,307,311,313,317,331,337,347,349
; Formula: a(n) = A093007(A000040(n)-1)/2

seq $0,40 ; The prime numbers.
sub $0,1
seq $0,93007 ; First nonprime number reached when iterating n under x->2*x+1.
div $0,2
