; A320927: Concatenation of successive segments generated by the morphism {0 -> {0, 0, 1}, 1 -> {0,1,0}}, starting with 0.
; Submitted by Stephen Uitti
; 0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1,0

add $0,1
mov $2,1
lpb $0
  add $2,$3
  dif $2,$4
  mov $3,$0
  add $3,1
  mod $3,3
  mov $4,$3
  sub $3,1
  mul $3,$2
  div $0,3
  add $1,$3
lpe
mov $0,$1
add $0,1
mod $0,2
