; A320927: Concatenation of successive segments generated by the morphism {0 -> {0, 0, 1}, 1 -> {0,1,0}}, starting with 0.
; Submitted by zombie67 [MM]
; 0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1,0
; Formula: a(n) = -2*truncate((A189727(2*n+1)+1)/2)+A189727(2*n+1)+1

#offset 1

mul $0,2
add $0,1
seq $0,189727 ; Fixed point of the morphism 0->011, 1->110.
add $0,1
mod $0,2
