; A186783: Diameter of the symmetric group S_n when generated by the transposition (1,2) and both left and right rotations by (1,2,...,n).
; 0,1,2,6,10,15,21,28,36,45,55,66,78

mov $2,2
cmp $2,$0
bin $1,$2
add $1,$0
mul $0,$1
mov $1,$0
div $1,2
