; A088520: Permutation of natural numbers generated by 3-rowed array shown below.
; 1,5,2,7,4,3,11,8,6,13,10,9,17,14,12,19,16,15,23,20,18,25,22,21,29,26,24,31,28,27,35,32,30,37,34,33,41,38,36,43,40,39,47,44,42,49,46,45,53,50,48,55,52,51,59,56,54,61,58,57,65,62,60,67,64,63,71,68,66,73,70,69
; Formula: a(n) = A131717(A116551(n))

seq $0,116551 ; Permutation of natural numbers generated by 3-rowed array shown below.
seq $0,131717 ; Natural numbers A000027 with 6n+4 and 6n+5 terms swapped.
