; A088520: Permutation of natural numbers generated by 3-rowed array shown below.
; Submitted by loader3229
; 1,5,2,7,4,3,11,8,6,13,10,9,17,14,12,19,16,15,23,20,18,25,22,21,29,26,24,31,28,27,35,32,30,37,34,33,41,38,36,43,40,39,47,44,42,49,46,45,53,50,48,55,52,51,59,56,54,61,58,57,65,62,60,67,64,63,71,68,66,73,70,69

#offset 1

mov $1,1
mov $2,5
mov $3,2
mov $4,7
mov $5,4
mov $6,3
mov $7,11
mov $8,8
mov $9,6
sub $0,1
lpb $0
  mul $1,0
  rol $1,9
  sub $9,$3
  add $9,$4
  add $9,$4
  sub $9,$5
  sub $9,$5
  add $9,$6
  add $9,$6
  sub $9,$7
  sub $9,$7
  add $9,$8
  add $9,$8
  sub $0,1
lpe
mov $0,$1
