; A054584: Number of subgroups of the group generated by a^n=1, b^3=1 and ab=ba.
; Submitted by FritzB
; 2,4,6,6,4,12,4,8,10,8,4,18,4,8,12,10,4,20,4,12,12,8,4,24,6,8,14,12,4,24,4,12,12,8,8,30,4,8,12,16,4,24,4,12,20,8,4,30,6,12,12,12,4,28,8,16,12,8,4,36,4,8,20,14,8,24,4,12,12,16,4,40,4,8,18,12,8,24,4,20

#offset 1

mov $1,1
mov $2,2
mov $4,1
lpb $0
  mov $3,$0
  lpb $3
    mov $4,$0
    mod $4,$2
    min $4,1
    add $2,1
    sub $3,$4
    sub $4,$6
    add $6,$4
    add $4,1
  lpe
  mov $5,1
  lpb $0
    dif $0,$2
    add $5,$4
  lpe
  mul $1,$5
lpe
mov $0,$1
mul $0,2
