; A247976: Triangle read by rows: T(n,k) generated by m-gon expansions in the case of odd m with "vertex to vertex" version or even m with "vertex to side" version. (See comment for details.)
; Submitted by Skillz
; 1,1,1,1,1,2,1,2,1,2,1,2,1,3,3,1,3,3,1,3,3,1,3,3,1,4,6,4,1,4,6,4,1,4,6,4,1,4,6,4,1,5,10,10,5,1,5,10,10,5,1,5,10,10,5,1,5,10,10,5,1,6,15,20,15,6,1,6,15,20,15,6,1,6,15,20,15,6,1,6,15,20,15,6,1,7,21,35,35,21,7,1,7,21,35,35,21,7,1,7

lpb $0
  add $2,1
  sub $0,$2
  add $1,1
  mov $2,$1
  div $2,4
lpe
add $2,1
bin $2,$0
mov $0,$2
