; A247502: Triangle read by rows: coefficients of polynomials related to the exponential generating function of sequences generated by Narayana polynomials evaluated at the integers; n>=1, 0<=k<n.
; Submitted by loader3229
; 1,1,1,1,4,1,1,13,9,1,1,41,57,16,1,1,131,320,165,25,1,1,428,1711,1420,380,36,1,1,1429,8967,11151,4620,756,49,1,1,4861,46663,83202,49665,12306,1358,64,1,1,16795,242634,602407,495327,172893,28476,2262,81,1

#offset 1

mov $2,$0
mul $2,8
nrt $2,2
add $2,1
div $2,2
mov $1,$2
bin $1,2
sub $0,$1
sub $0,1
mov $3,$0
sub $2,$0
lpb $2
  sub $2,1
  mov $4,$1
  add $4,$3
  add $4,1
  mov $7,$4
  mul $7,8
  nrt $7,2
  sub $7,1
  div $7,2
  mov $8,$7
  add $8,1
  bin $8,2
  sub $4,$8
  sub $4,1
  mov $8,$7
  add $8,1
  bin $8,$4
  bin $7,$4
  add $4,1
  mul $7,$8
  div $7,$4
  add $3,1
  mov $5,$3
  bin $5,2
  add $5,$0
  mov $11,$5
  mul $11,8
  nrt $11,2
  add $11,1
  div $11,2
  bin $11,2
  mov $10,$5
  sub $10,$11
  mov $12,0
  sub $12,$10
  fac $10,$12
  mov $9,$5
  seq $9,131689 ; Triangle of numbers T(n,k) = k!*Stirling2(n,k) = A000142(k)*A048993(n,k) read by rows, T(n, k) for 0 <= k <= n.
  div $9,$10
  mov $4,$7
  mul $4,$9
  add $6,$4
lpe
mov $0,$6
