; A072844: Number of words of length 2n-1 generated by the two letters s and t that reduce to the identity 1 by using the relations sssssss=1, tt=1 and stst=1. The generators s and t along with the three relations generate the 14-element dihedral group D7.
; Submitted by loader3229
; 0,0,0,1,9,55,286,1365,6188,27132,116281,490337,2043275,8439210,34621041,141290436,574274008,2326683921,9402807817,37923176863,152705590518,614111175965,2467123420524,9903167265124,39725253489545
; Formula: a(n) = b(n-1), b(n) = 25*b(n-3)+9*b(n-1)-4*b(n-4)-26*b(n-2), b(8) = 6188, b(7) = 1365, b(6) = 286, b(5) = 55, b(4) = 9, b(3) = 1, b(2) = 0, b(1) = 0, b(0) = 0

#offset 1

mov $4,1
sub $0,1
lpb $0
  mul $1,-4
  rol $1,4
  mov $5,$1
  mul $5,25
  add $4,$5
  mov $5,$2
  mul $5,-26
  add $4,$5
  mov $5,$3
  mul $5,9
  sub $0,1
  add $4,$5
lpe
mov $0,$1
