; A072844: Number of words of length 2n+1 generated by the two letters s and t that reduce to the identity 1 by using the relations sssssss=1, tt=1 and stst=1. The generators s and t along with the three relations generate the 14-element dihedral group D7.
; Submitted by Jon Maiga
; 0,0,0,1,9,55,286,1365,6188,27132,116281,490337,2043275,8439210,34621041,141290436,574274008,2326683921,9402807817,37923176863,152705590518,614111175965,2467123420524,9903167265124,39725253489545

mov $1,1
mul $0,2
lpb $0
  sub $0,1
  mov $2,$1
  mul $2,2
  sub $3,$1
  add $1,$3
  mul $3,2
  sub $3,$4
  mov $4,$2
  add $4,$1
  add $5,$2
  mov $2,$3
  mov $3,$5
  add $5,$2
lpe
mov $0,$3
div $0,2
