; A072844: Number of words of length 2n-1 generated by the two letters s and t that reduce to the identity 1 by using the relations sssssss=1, tt=1 and stst=1. The generators s and t along with the three relations generate the 14-element dihedral group D7.
; Submitted by [AF>Amis des Lapins] Jean-Luc
; 0,0,0,1,9,55,286,1365,6188,27132,116281,490337,2043275,8439210,34621041,141290436,574274008,2326683921,9402807817,37923176863,152705590518,614111175965,2467123420524,9903167265124,39725253489545
; Formula: a(n) = b(2*n+1), b(n) = 2*c(n-2)-c(n-1)+c(n-3), b(7) = 1, b(6) = 10, b(5) = 0, b(4) = 3, b(3) = 0, b(2) = 1, b(1) = 0, b(0) = 1, c(n) = 5*c(n-2)-2*c(n-5)-5*c(n-4)+c(n-3), c(9) = 265, c(8) = 163, c(7) = 65, c(6) = 42, c(5) = 16, c(4) = 11, c(3) = 4, c(2) = 3, c(1) = 1, c(0) = 1

mov $3,1
mov $4,1
mov $5,1
mul $0,2
add $0,1
lpb $0
  sub $0,1
  add $1,$3
  sub $3,$4
  mov $4,$2
  add $5,$2
  mov $2,$3
  mov $3,$5
  add $4,$1
  sub $4,$5
  add $5,$4
  add $5,$2
lpe
mov $0,$4
