; A070734: Order of the subgroup of the symmetric group S_n generated by the cycles (1,2,3) and (1,2,3,...,n).
; Submitted by vaughan
; 3,24,60,720,2520,40320,181440,3628800,19958400,479001600,3113510400,87178291200,653837184000,20922789888000,177843714048000,6402373705728000,60822550204416000,2432902008176640000
; Formula: a(n) = truncate(b(n)/gcd(n-3,2)), b(n) = n*b(n-1), b(0) = 1

#offset 3

sub $0,3
mov $2,1
mov $1,$0
add $1,3
lpb $1
  mul $2,$1
  sub $1,1
lpe
gcd $0,2
mov $1,$2
div $1,$0
mov $0,$1
