; A070886: Triangle read by rows giving successive states of cellular automaton generated by "Rule 90".
; Submitted by Science United
; 1,1,0,1,1,0,0,0,1,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,1,0,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
; Formula: a(n) = -2*truncate(binomial(2*sqrtint(n),-sqrtint(n)^2+n)/2)+binomial(2*sqrtint(n),-sqrtint(n)^2+n)

mov $1,$0
nrt $1,2
mov $2,$1
mul $2,$1
sub $0,$2
mul $1,2
bin $1,$0
mov $0,$1
mod $0,2
