; A070886: Triangle read by rows giving successive states of cellular automaton generated by "Rule 90".
; Submitted by vaughan
; 1,1,0,1,1,0,0,0,1,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,1,0,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1

mov $2,1
trn $0,1
lpb $0
  add $2,2
  sub $0,$2
lpe
mov $1,$2
bin $1,$0
sub $0,1
bin $2,$0
add $1,$2
mod $1,2
mov $0,$1
