; A070909: Triangle read by rows giving successive states of cellular automaton generated by "Rule 28" and by "Rule 156".
; Submitted by Stony666
; 1,1,1,1,0,1,1,0,1,1,1,0,1,0,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0

mov $2,0
lpb $0
  add $2,1
  sub $0,$2
lpe
sub $2,$0
mov $1,1
add $1,$0
pow $1,$2
mov $0,$1
mod $0,2
