; A070734: Order of the subgroup of the symmetric group S_n generated by the cycles (1,2,3) and (1,2,3,...,n).
; 3,24,60,720,2520,40320,181440,3628800,19958400,479001600,3113510400,87178291200,653837184000,20922789888000,177843714048000,6402373705728000,60822550204416000,2432902008176640000

add $0,3
mov $1,$0
gcd $0,2
seq $1,142 ; Factorial numbers: n! = 1*2*3*4*...*n (order of symmetric group S_n, number of permutations of n letters).
mul $0,$1
div $0,6
mul $0,3
