; A070886: Triangle read by rows giving successive states of cellular automaton generated by "Rule 90".
; 1,1,0,1,1,0,0,0,1,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,1,0,0,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
; Formula: a(n) = A034870(n)%2

seq $0,34870 ; Even-numbered rows of Pascal's triangle.
mod $0,2
