; A141326: Subsequence of 'Fermat near misses' which is generated by a simple formula based on the cubic binomial expansion along with formulas for the corresponding terms in the expression, x^3 + y^3 = z^3 + 1.
; 12,150,738,2316,5640,11682,21630,36888,59076,90030,131802,186660,257088,345786,455670,589872,751740,944838,1172946,1440060,1750392,2108370,2518638,2986056,3515700,4112862,4783050,5531988,6365616,7290090,8311782,9437280,10673388

mov $3,$0
add $0,1
pow $0,4
mov $2,4
mul $2,$0
mov $4,$0
sub $4,$2
lpb $0,1
  mov $2,1
  sub $2,$0
  add $0,$2
  sub $0,1
  mov $2,7
  sub $3,$4
  add $3,11
lpe
add $3,$2
mov $1,$3
div $1,2
sub $1,8
mul $1,6
