; A267598: Triangle read by rows giving successive states of cellular automaton generated by "Rule 177" initiated with a single ON (black) cell.
; 1,0,0,1,0,1,0,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0

mov $3,$0
mov $1,1
mov $6,$3
mov $4,6
mov $0,$1
mov $4,2
mov $2,$0
mov $5,4
sub $0,$6
fac $5
mov $6,1
div $1,$6
mod $4,$2
mov $0,$3
add $4,4
lpb $2,1
  sub $2,$1
  add $6,$2
  mov $2,2
  add $0,2
  mov $4,$3
  add $4,6
  sub $4,4
  lpb $4,1
    add $6,$2
    mov $1,$4
    add $3,2
    sub $4,$6
    mov $3,$4
    gcd $1,2
  lpe
  add $4,4
  mov $5,3
  add $2,$3
  mul $2,3
  mul $5,$3
  lpb $5,1
    div $6,$0
    add $6,$2
    sub $2,18
    sub $5,$6
    sub $3,1
    add $1,$0
    sub $6,1
    mov $0,1
  lpe
  fac $2
  lpb $6,1
    sub $3,1
    mov $0,1
    sub $5,$6
    mov $2,$5
    add $3,$2
    sub $6,$6
  lpe
  mov $5,2
  sub $2,1
lpe
mov $6,2
mul $2,2
sub $1,1
