; A267683: Triangle read by rows giving successive states of cellular automaton generated by "Rule 203" initiated with a single ON (black) cell.
; 1,1,0,0,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1

mov $1,$0
mov $2,1
mov $2,$0
mul $1,2
mov $4,1
gcd $4,$0
add $0,1
lpb $2,1
  mov $5,$2
  mul $2,2
  mov $5,$0
  lpb $4,1
    mov $6,1
    mov $3,2
    mov $3,$0
    mov $6,2
    add $3,1
    bin $2,$2
    sub $4,$4
    add $3,1
    add $0,$0
    trn $5,1
  lpe
  pow $6,10
  sub $3,4
  pow $1,$4
  lpb $5,1
    mul $1,6
    sub $2,$2
    trn $0,1
    add $4,2
    add $3,1
    sub $5,$4
  lpe
  add $6,4
  add $1,1
  trn $4,$0
  lpb $6,1
    mov $0,$1
    mul $6,$2
    div $0,2
    mul $5,$0
    sub $6,$4
    trn $6,1
    mov $6,1
  lpe
  mov $1,5
  sub $0,$0
  sub $1,$2
  sub $3,1
  sub $2,1
  add $2,$5
lpe
add $5,$0
sub $5,28
mov $0,$4
mov $5,$0
pow $1,2
cmp $6,$3
add $6,$4
mov $1,$0
