; A165674: Triangle generated by the asymptotic expansions of the E(x,m=2,n).
; Submitted by Science United
; 1,3,1,11,5,1,50,26,7,1,274,154,47,9,1,1764,1044,342,74,11,1,13068,8028,2754,638,107,13,1,109584,69264,24552,5944,1066,146,15,1,1026576,663696,241128,60216,11274,1650,191,17,1

#offset 1

mov $2,$0
mul $2,8
nrt $2,2
sub $2,1
div $2,2
mov $3,$2
add $3,1
bin $3,2
add $2,1
sub $0,$3
sub $0,$2
sub $0,1
gcd $0,0
mov $1,2
sub $2,$0
lpb $0
  sub $0,1
  add $2,1
  mul $4,$2
  add $4,$1
  mul $1,$2
lpe
mov $0,$4
div $0,2
