; A165674: Triangle generated by the asymptotic expansions of the E(x,m=2,n).
; Submitted by Jamie Morken(w4)
; 1,3,1,11,5,1,50,26,7,1,274,154,47,9,1,1764,1044,342,74,11,1,13068,8028,2754,638,107,13,1,109584,69264,24552,5944,1066,146,15,1,1026576,663696,241128,60216,11274,1650,191,17,1

#offset 1

sub $0,1
lpb $0
  add $2,1
  sub $0,$2
lpe
mov $1,1
mov $3,1
sub $0,$2
add $2,1
dif $0,-1
lpb $0
  sub $0,1
  mul $1,$2
  sub $2,1
  mul $3,$2
  add $3,$1
lpe
mov $0,$3
