; A226136: Positions of the positive integers in the ordering of rational numbers as generated by the rules: 1 is in S, and if nonzero x is in S, then x+1 and -1/x are in S.  (See Comments.)
; Submitted by loader3229
; 1,2,4,7,10,15,22,32,47,69,101,148,217,318,466,683,1001,1467,2150,3151,4618,6768,9919,14537,21305,31224,45761,67066,98290,144051,211117,309407,453458,664575,973982,1427440

#offset 1

mov $1,1
mov $2,2
mov $3,4
mov $4,7
mov $5,10
mov $6,15
sub $0,1
lpb $0
  mul $1,0
  rol $1,6
  add $6,$3
  add $6,$5
  sub $0,1
lpe
mov $0,$1
