; A226041: Primes generated by concatenation of three consecutive numbers divided by three.
; Submitted by [AF>Amis des Lapins] Ceclo
; 41,263,50539,64007,151549,191953,205421,232357,252559,266027,272761,306431,326633,35035369,39039373,52386053,62396063,70404071,77077411,82416083,96430097,103103437,106440107,110444111

mov $1,1
mov $2,$0
add $2,2
pow $2,2
mul $2,2
lpb $2
  mov $3,$1
  seq $3,74991 ; Concatenation of n, n+1, n+2 divided by 3.
  sub $3,1
  mov $5,$3
  div $5,2
  seq $3,10051 ; Characteristic function of primes: 1 if n is prime, else 0.
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  trn $2,1
lpe
mov $0,$5
mul $0,2
add $0,1
