; A226482: Number of runs of consecutive ones and zeros in successive states of cellular automaton generated by "Rule 30".
; Submitted by Science United
; 1,1,3,3,5,5,7,5,7,9,11,11,13,13,15,13,13,15,19,17,17,21,27,23,21,23,29,31,27,29,33,27,29,33,39,35,35,35,41,41,33,37,41,39,45,43,45,43,45,41,53,59,51,53,57,57,55,55,65,61,59,61,71,63,55,57,65,65,65,69,75,61,55,73,75,79,85,83,87,83

sub $0,1
mov $1,1
mov $4,$0
add $4,1
lpb $4
  sub $4,1
  mov $2,$1
  mul $2,2
  bxo $2,$1
  add $1,$2
  bxo $1,$2
lpe
mov $3,$1
div $3,2
mov $0,$1
bxo $0,$3
dgs $0,2
div $0,2
mul $0,2
add $0,1
