; A226482: Number of runs of consecutive ones and zeros in successive states of cellular automaton generated by "Rule 30".
; Submitted by [AF>Amis des Lapins] Jean-Luc
; 1,1,3,3,5,5,7,5,7,9,11,11,13,13,15,13,13,15,19,17,17,21,27,23,21,23,29,31,27,29,33,27,29,33,39,35,35,35,41,41,33,37,41,39,45,43,45,43,45,41,53,59,51,53,57,57,55,55,65,61,59,61,71,63,55,57,65,65,65,69,75,61,55,73,75,79,85,83,87,83,69,77,87,93,93,83,91,81,71,79,101,89,85,87,95,95,93,93,115,113
; Formula: a(n) = 2*(A005811(A110240(n)/4)/2)+1

seq $0,110240 ; Decimal form of binary integer produced by the ON cells at n-th generation following Wolfram's Rule 30 cellular automaton starting from a single ON-cell represented as 1.
div $0,4
seq $0,5811 ; Number of runs in binary expansion of n (n>0); number of 1's in Gray code for n.
div $0,2
mul $0,2
add $0,1
