; A226136: Positions of the positive integers in the ordering of rational numbers as generated by the rules: 1 is in S, and if nonzero x is in S, then x+1 and -1/x are in S.  (See Comments.)
; Submitted by BrandyNOW
; 1,2,4,7,10,15,22,32,47,69,101,148,217,318,466,683,1001,1467,2150,3151,4618,6768,9919,14537,21305,31224,45761,67066,98290,144051,211117,309407,453458,664575,973982,1427440
; Formula: a(n) = e(n-1), b(n) = d(n-1), b(3) = 3, b(2) = 1, b(1) = 0, b(0) = 1, c(n) = (c(n-1)==1)+d(n-2), c(3) = 2, c(2) = 1, c(1) = 1, c(0) = 0, d(n) = (c(n-1)==1)+(c(n-2)==1)+d(n-1)+d(n-3), d(4) = 7, d(3) = 5, d(2) = 3, d(1) = 1, d(0) = 0, e(n) = 2*(c(n-1)==1)+b(n-1)+e(n-1), e(3) = 7, e(2) = 4, e(1) = 2, e(0) = 1

#offset 1

mov $1,1
mov $4,1
sub $0,1
lpb $0
  sub $0,1
  equ $2,1
  add $4,$2
  add $2,$1
  mov $1,$3
  mov $3,$4
  add $4,$2
lpe
mov $0,$4
