; A039727: [ Even numbers in the sequence generated by b(n)=|b(n-1)+2b(n-2)-n| ], divided by 2.
; Submitted by Jamie Morken(w1)
; 0,0,1,0,3,0,1,4,3,4,5,5,4,7,0,0,13,2,9,4,7,9,10,10,9,14,7,6,13,22,7,13,12,19,8,5,16,11,16,32,5,18,19,11,18,32,5,12,7,3,12,19,22,37,14,18,25,46,7,26,25,23,28,36,19,12,53,3,34,15,0,40,29,21,10,2,9,54,15,14,57,35

trn $0,1
seq $0,50821 ; Even numbers in the sequence generated by a(n)=|a(n-1)+2a(n-2)-n|.
div $0,2
