; A234939: Coefficients of Hilbert series for suboperad of bicolored noncrossing configurations generated by a triangle with colored base and at least one more colored edge and a triangle with one colored non-base edge.
; Submitted by [AF>Amis des Lapins] Ceclo
; 1,2,8,38,200,1124,6608,40142,249992,1587548,10241264,66926204,442120016,2947660616,19808372384,134030802782,912385334792,6244056445868,42935538999728,296493196682036,2055313327353200,14297177397185912,99769106353379168,698228176760193068

#offset 1

sub $0,1
mov $2,1
mov $3,1
mov $5,2
mov $4,$0
lpb $4
  mul $2,$4
  sub $4,1
  add $6,$5
  mul $2,$4
  div $2,$6
  mul $3,3
  add $3,$2
  add $5,2
lpe
mov $1,2
max $1,$3
mov $0,$1
mul $0,2
div $0,3
