; A234939: Coefficients of Hilbert series for suboperad of bicolored noncrossing configurations generated by a triangle with colored base and at least one more colored edge and a triangle with one colored non-base edge.
; Submitted by Solidair79
; 1,2,8,38,200,1124,6608,40142,249992,1587548,10241264,66926204,442120016,2947660616,19808372384,134030802782,912385334792,6244056445868,42935538999728,296493196682036,2055313327353200,14297177397185912,99769106353379168,698228176760193068
; Formula: a(n) = truncate(b(n)/3), b(n) = truncate((4*d(n-1)+2*c(n-1))/(-n)), b(3) = 24, b(2) = 6, b(1) = 4, b(0) = 0, c(n) = 6*d(n-1)+4*c(n-1), c(3) = -132, c(2) = -24, c(1) = -6, c(0) = 0, d(n) = 4*d(n-1)+2*c(n-1)+truncate((4*d(n-1)+2*c(n-1))/(-n)), d(3) = -48, d(2) = -6, d(1) = 0, d(0) = -1

#offset 1

mov $3,-1
lpb $0
  sub $0,1
  add $2,$3
  add $3,$2
  mul $3,2
  sub $4,1
  mov $1,$3
  div $1,$4
  mul $2,2
  add $2,$3
  add $3,$1
lpe
div $1,3
mov $0,$1
