; A083692: Length of list generated by n replacements of k by {-1-|k|, .., 1+|k|} with increment 2, starting with {1}.
; Submitted by fzs600
; 1,3,10,38,148,620,2600,11480,50256,229296,1032352,4816736,22118720,104890048,488768128,2346515840,11058545920,53605825280,254908828160,1245304583680,5965139153920,29328419056640,141339991746560

mov $3,1
mov $6,1
add $0,1
mul $0,2
lpb $0
  sub $0,2
  mov $1,$5
  mul $1,12
  add $4,3
  mov $5,$3
  mov $3,$1
  mul $1,$2
  div $1,$4
  mov $2,$0
  add $3,$1
  max $1,$6
  add $6,$1
lpe
mov $0,$6
div $0,2
