; A083691: Length of list generated by n replacements of k by {-1-|k|, ..., 1+|k|} with increment 2, starting with {0}.
; Submitted by Science United
; 1,2,6,20,76,296,1240,5200,22960,100512,458592,2064704,9633472,44237440,209780096,977536256,4693031680,22117091840,107211650560,509817656320,2490609167360,11930278307840,58656838113280,282679983493120

mov $3,1
mov $6,1
mul $0,2
lpb $0
  sub $0,2
  mov $1,$5
  mul $1,12
  add $4,3
  mov $5,$3
  mov $3,$1
  mul $1,$2
  div $1,$4
  mov $2,$0
  add $3,$1
  max $1,$6
  add $6,$1
lpe
mov $0,$6
