; A083692: Length of list generated by n replacements of k by {-1-|k|, .., 1+|k|} with increment 2, starting with {1}.
; Submitted by fzs600
; 1,3,10,38,148,620,2600,11480,50256,229296,1032352,4816736,22118720,104890048,488768128,2346515840,11058545920,53605825280,254908828160,1245304583680,5965139153920,29328419056640,141339991746560
; Formula: a(n) = truncate(A083691(n+1)/2)

add $0,1
seq $0,83691 ; Length of list generated by n replacements of k by {-1-|k|, ..., 1+|k|} with increment 2, starting with {0}.
div $0,2
