; A083693: Sum of absolute values of list generated by n replacements of k by {-1-|k|, .., 1+|k|} with increment 2, starting with {1}.
; Submitted by LCB001
; 1,4,18,72,324,1360,6280,27296,128784,573760,2752032,12485248,60652608,278988032,1368979584,6365514240,31488733440,147697177600,735486927360,3474529986560,17398140748800,82683153633280,415966710171648

mov $4,$0
mov $3,2
lpb $3
  div $3,2
  mov $0,$4
  add $0,$3
  add $0,1
  seq $0,83691 ; Length of list generated by n replacements of k by {-1-|k|, ..., 1+|k|} with increment 2, starting with {0}.
  div $0,2
  mov $2,$3
  mul $2,$0
  add $1,$2
  mov $5,$0
lpe
mul $5,2
sub $1,$5
mov $0,$1
