; A059769: Frobenius number of the subsemigroup of the natural numbers generated by successive pairs of Fibonacci numbers.
; Submitted by loader3229
; 1,7,27,83,239,659,1781,4751,12583,33175,87231,228983,600473,1573655,4122467,10796939,28273519,74031979,193835949,507497759,1328692751,3478637807,9107313407,23843452463,62423286769,163426800679,427857750891,1120147480451
; Formula: a(n) = c(n-2)*b(n-2)-1, b(n) = b(n-1)+b(n-2)+1, b(2) = 2, b(1) = 1, b(0) = 0, c(n) = c(n-1)+c(n-2)+1, c(1) = 2, c(0) = 1

#offset 3

mov $3,1
sub $0,2
lpb $0
  sub $0,1
  add $2,1
  ror $2,2
  add $3,$2
lpe
mul $2,$3
mov $0,$2
sub $0,1
