; A059769: Frobenius number of the subsemigroup of the natural numbers generated by successive pairs of Fibonacci numbers.
; Submitted by Jamie Morken(s3)
; 1,7,27,83,239,659,1781,4751,12583,33175,87231,228983,600473,1573655,4122467,10796939,28273519,74031979,193835949,507497759,1328692751,3478637807,9107313407,23843452463,62423286769,163426800679,427857750891,1120147480451
; Formula: a(n) = b(n)*(c(n)+d(n))-1, b(n) = c(n-1)+d(n-1), b(2) = 4, b(1) = 2, b(0) = 1, c(n) = c(n-1)+d(n-1), c(2) = 4, c(1) = 2, c(0) = 1, d(n) = c(n-2)+d(n-2)+1, d(2) = 3, d(1) = 2, d(0) = 1

mov $3,1
add $0,1
lpb $0
  sub $0,1
  add $2,$3
  mov $3,$1
  add $3,1
  mov $1,$2
lpe
add $3,$2
mul $1,$3
mov $0,$1
sub $0,1
