; A117999: Decimal number generated by the binary bits of the n-th generation of the Rule 110 elementary cellular automaton.
; Submitted by [AF>France>Ouest>Normandie]The Stress Man (-:
; 1,6,28,104,496,1568,7360,27520,130304,396800,1848320,6879232,32706560,103702528,485867520,1799258112,8569421824,25897336832,120686641152,448682000384,2137705676800,6768178495488,31718320898048,118691479945216,558749693509632
; Formula: a(n) = 2*A161903(a(n-1)), a(0) = 1

mov $1,1
lpb $0
  sub $0,1
  seq $1,161903 ; Convert n into a sequence of binary digits, apply one step of the rule 110 cellular automaton, and interpret the results as a binary integer.
  mul $1,2
lpe
mov $0,$1
