; A129703: Number of different walks generated by n steps that can only go in {east, southeast, southwest} directions on the 300-degree wedge in a 60-degree equilateral triangular lattice.
; Submitted by Jon Maiga
; 1,3,6,14,36,97,268,751,2124,6047,17304,49722,143366,414585,1201918,3492118,10165780,29643871,86574832,253188112,741365050,2173243129,6377181826,18730782253,55062586342,161995031227,476941691178

mov $3,$0
mov $4,$0
lpb $4
  sub $4,1
  mov $0,$3
  sub $0,$4
  mov $1,1
  add $1,$0
  add $0,1
  seq $0,132894 ; Number of (1,0) steps in all paths of length n with steps U=(1,1), D=(1,-1) and H=(1,0), starting at (0,0), staying weakly above the x-axis (i.e., in all length-n left factors of Motzkin paths).
  mov $2,$0
  gcd $2,$1
  pow $2,2
  mul $0,91
  mul $1,$0
  div $1,$2
lpe
mov $0,$1
div $0,91
add $0,1
