; A129703: Number of different walks generated by n steps that can only go in {east, southeast, southwest} directions on the 300-degree wedge in a 60-degree equilateral triangular lattice.
; Submitted by swezy
; 1,3,6,14,36,97,268,751,2124,6047,17304,49722,143366,414585,1201918,3492118,10165780,29643871,86574832,253188112,741365050,2173243129,6377181826,18730782253,55062586342,161995031227,476941691178

mov $1,$0
mul $1,2
mov $2,$0
add $2,1
add $0,1
div $1,$2
mov $6,$0
add $0,2
lpb $0
  mov $4,$0
  add $4,$6
  sub $0,2
  div $4,2
  bin $4,$0
  mov $5,$6
  sub $5,1
  bin $5,$3
  mul $5,$4
  add $3,1
  add $7,$5
lpe
mov $0,$7
div $0,2
mul $0,$1
add $0,1
