; A129703: Number of different walks generated by n steps that can only go in {east, southeast, southwest} directions on the 300-degree wedge in a 60-degree equilateral triangular lattice.
; Submitted by Kotenok2000
; 1,3,6,14,36,97,268,751,2124,6047,17304,49722,143366,414585,1201918,3492118,10165780,29643871,86574832,253188112,741365050,2173243129,6377181826,18730782253,55062586342,161995031227,476941691178

mul $0,2
mov $1,1
mov $2,$0
mov $3,1
mov $6,1
mov $7,1
lpb $0
  sub $0,2
  add $3,$1
  add $4,2
  add $1,$5
  mov $5,$3
  mov $3,$1
  mul $1,$2
  div $1,$4
  mov $2,$0
  add $3,$1
  sub $6,$7
  trn $6,-1
  add $6,$1
  add $7,$6
lpe
mov $0,$7
