; A273465: Numbers generated by starting at 1 and adding twice and subtracting once following the sequence of positive integers.
; Submitted by loader3229
; 1,3,6,2,7,13,6,14,23,13,24,36,23,37,52,36,53,71,52,72,93,71,94,118,93,119,146,118,147,177,146,178,211,177,212,248,211,249,288,248,289,331,288,332,377,331,378,426,377,427,478,426,479,533,478,534,591,533,592,652,591,653,716,652,717,783,716,784,853,783,854,926,853,927,1002,926,1003,1081,1002,1082

#offset 1

mov $1,1
mov $2,3
mov $3,6
mov $4,2
mov $5,7
mov $6,13
mov $7,6
sub $0,1
lpb $0
  rol $1,7
  sub $7,$1
  sub $7,$3
  sub $7,$3
  add $7,$4
  add $7,$4
  add $7,$6
  sub $0,1
lpe
mov $0,$1
