; A273465: Numbers generated by starting at 1 and adding twice and subtracting once following the sequence of positive integers.
; Submitted by Checco
; 1,3,6,2,7,13,6,14,23,13,24,36,23,37,52,36,53,71,52,72,93,71,94,118,93,119,146,118,147,177,146,178,211,177,212,248,211,249,288,248,289,331,288,332,377,331,378,426,377,427,478,426,479,533,478,534,591,533,592,652,591,653,716,652,717,783,716,784,853,783,854,926,853,927,1002,926,1003,1081,1002,1082
; Formula: a(n) = n*floor((gcd(n,3)+n)/3)-floor((n*(n+1))/2)+floor((n*(n+1))/3)+2

#offset 1

mov $1,$0
gcd $0,3
add $0,$1
div $0,3
mul $0,$1
fac $1,2
mov $2,$1
div $2,3
div $1,2
sub $0,$1
add $0,$2
add $0,2
