; A191106: Increasing sequence generated by these rules: a(1)=1, and if x is in a then 3x-2 and 3x are in a.
; 1,3,7,9,19,21,25,27,55,57,61,63,73,75,79,81,163,165,169,171,181,183,187,189,217,219,223,225,235,237,241,243,487,489,493,495,505,507,511,513,541,543,547,549,559,561,565,567,649,651,655,657,667,669,673,675,703,705,709,711,721,723,727,729,1459,1461,1465,1467,1477

mov $11,$0
mov $13,$0
add $13,1
lpb $13,1
  clr $0,11
  sub $13,1
  mov $0,$11
  sub $0,$13
  mov $7,$0
  mov $9,2
  lpb $9,1
    clr $0,7
    sub $9,1
    mov $0,$7
    add $0,$9
    sub $0,1
    mov $4,$0
    mov $6,$0
    add $6,1
    lpb $6,1
      clr $0,4
      sub $6,1
      mov $0,$4
      sub $0,$6
      lpb $0,1
        add $2,2
        add $1,1
        mov $3,3
        gcd $0,262144
        mov $2,$2
        div $0,2
        add $2,$0
        mul $1,3
      lpe
      mov $2,2
      add $1,$3
      mul $1,12
      mul $0,$3
      div $1,27
      add $1,1
      add $5,$1
    lpe
    mov $1,$5
    mov $10,$9
    lpb $10,1
      mov $8,$1
      sub $10,1
    lpe
  lpe
  lpb $7,1
    sub $8,$1
    mov $7,0
  lpe
  mov $1,$8
  sub $1,1
  div $1,2
  add $1,1
  add $12,$1
lpe
mov $1,$12
