; A383671: The limiting word that starts with 0, as a sequence, generated by s(0) = 0, s(1) = 12, s(n) = concatenation of s(n - 2) and s(n - 1).
; Submitted by mmonnin
; 0,1,2,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,1,2,0,1
; Formula: a(n) = -truncate(gcd(2*truncate((-c(n-1)+b(n-1))/4)+a(n-1)+8,4)/2)+2, a(2) = 2, a(1) = 1, a(0) = 0, b(n) = if((truncate(gcd(2*truncate((-c(n-1)+b(n-1))/4)+a(n-1)+8,4)/2)-2)==0,2*truncate((-c(n-1)+b(n-1))/4)+8,if(((2*truncate((-c(n-1)+b(n-1))/4)+8)%(truncate(gcd(2*truncate((-c(n-1)+b(n-1))/4)+a(n-1)+8,4)/2)-2))==0,(2*truncate((-c(n-1)+b(n-1))/4)+8)/(truncate(gcd(2*truncate((-c(n-1)+b(n-1))/4)+a(n-1)+8,4)/2)-2),2*truncate((-c(n-1)+b(n-1))/4)+8)), b(2) = -1, b(1) = -6, b(0) = 0, c(n) = gcd(2*truncate((-c(n-1)+b(n-1))/4)+a(n-1)+8,4)*c(n-1), c(2) = 8, c(1) = 8, c(0) = 4

mov $2,4
lpb $0
  sub $0,1
  sub $1,$2
  div $1,4
  mul $1,2
  add $1,8
  add $3,$1
  gcd $3,4
  mul $2,$3
  div $3,2
  sub $3,2
  dif $1,$3
  mul $3,-1
lpe
mov $0,$3
