; A383422: The infinite Lucas word; the limiting word generated by s(0) = 0, s(1) = 011, and s(n) = s(n-1)s(n-2).
; Submitted by Science United
; 0,1,1,0,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,1,0,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,1,0,0,1,1,0,1,1,0,0,1,1,0,0,1,1,0,1,1,0,0,1,1,0,1,1,0,0,1,1,0
; Formula: a(n) = b(n+1)^e(n+1), b(n) = b(n-1), b(3) = 0, b(2) = 0, b(1) = 0, b(0) = 0, c(n) = if((2*floor(gcd(e(n-1)+truncate((-d(n-1)+c(n-1)-5)/4)+2,4)/2))==0,truncate((-d(n-1)+c(n-1)-5)/4)+2,if(((truncate((-d(n-1)+c(n-1)-5)/4)+2)%(2*floor(gcd(e(n-1)+truncate((-d(n-1)+c(n-1)-5)/4)+2,4)/2)))==0,(truncate((-d(n-1)+c(n-1)-5)/4)+2)/(2*floor(gcd(e(n-1)+truncate((-d(n-1)+c(n-1)-5)/4)+2,4)/2)),truncate((-d(n-1)+c(n-1)-5)/4)+2)), c(3) = -19, c(2) = -15, c(1) = 0, c(0) = 0, d(n) = d(n-1)*gcd(e(n-1)+truncate((-d(n-1)+c(n-1)-5)/4)+2,4)^2, d(3) = 64, d(2) = 64, d(1) = 64, d(0) = 4, e(n) = 2*floor(gcd(e(n-1)+truncate((-d(n-1)+c(n-1)-5)/4)+2,4)/2), e(3) = 0, e(2) = 0, e(1) = 4, e(0) = 0

mov $3,4
add $0,1
lpb $0
  sub $0,1
  sub $2,$3
  sub $2,5
  div $2,4
  add $2,2
  add $4,$2
  gcd $4,4
  mul $3,$4
  mul $3,$4
  div $4,2
  mul $4,2
  dif $2,$4
lpe
pow $1,$4
mov $0,$1
