; A383671: The limiting word that starts with 0, as a sequence, generated by s(0) = 0, s(1) = 12, s(n) = concatenation of s(n - 2) and s(n - 1).
; Submitted by mmonnin
; 0,1,2,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,0,1,2,1,2,0,1,2,1,2,0,1

mov $2,4
lpb $0
  sub $0,1
  sub $1,$2
  div $1,4
  mul $1,2
  add $1,8
  add $3,$1
  gcd $3,4
  mul $2,$3
  div $3,2
  sub $3,2
  dif $1,$3
  mul $3,-1
lpe
mov $0,$3
