; A070909: Triangle read by rows giving successive states of cellular automaton generated by "Rule 28" and by "Rule 156".
; 1,1,1,1,0,1,1,0,1,1,1,0,1,0,1,1,0,1,0,1,1,1,0,1,0,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0

mov $1,1
mov $4,$1
mov $1,1
mov $4,2
mov $2,$1
cal $1,105334
cal $0,128227
div $2,2
mov $1,2
add $1,1
mov $4,1
sub $0,$1
mul $2,2
sub $0,1
sub $0,$1
mod $0,2
bin $2,$0
mov $3,$2
mov $1,$0
sub $2,$0
mov $1,$3
