; A300931: a(n) is the number of Klein four orbits of permutations generated by the operations of inverse permutation and conjugation by w_0 = [n, n-1, ..., 1].
; Submitted by BrandyNOW
; 1,1,2,4,13,45,230,1388,10558,92126,912908,9998008,119831996,1557050972,21795929320,326923928048,5230723155848,88921965504136,1600593971537552,30411277553507360,608225514852464848,12772735603832679248,281000182274281641056,6463004186370603502912,155112100442546452767200,3877802510881077215518688,100822865281930654438698688,2722217362606111131503586176,76222086152937527846340450752,2210440498434976840831312108480,66313214953048078830180497180288,2055709663544482548455887917778688
; Formula: a(n) = truncate((2*A000085(n)+A000142(n)+A037223(n))/4)

mov $1,$0
seq $1,37223 ; Number of solutions to non-attacking rooks problem on n X n board that are invariant under 180-degree rotation.
mov $2,$0
seq $2,85 ; Number of self-inverse permutations on n letters, also known as involutions; number of standard Young tableaux with n cells.
mul $2,2
seq $0,142 ; Factorial numbers: n! = 1*2*3*4*...*n (order of symmetric group S_n, number of permutations of n letters).
add $0,$1
add $0,$2
div $0,4
