; A231873: Elements of the integer compositions sub-operad Comp of TN_2 generated by 00 and 010.
; Submitted by BrandyNOW
; 1,11,12,111,112,121,122,1111,1112,1121,1122,1211,1212,1221,1222,11111,11112,11121,11122,11211,11212,11221,11222,12111,12112,12121,12122,12211,12212,12221,12222

#offset 1

mov $1,1
lpb $0
  lpb $0
    dif $0,2
    add $2,$1
    mul $1,10
  lpe
  add $2,$1
  div $0,2
  mul $0,2
lpe
add $0,$2
