; A231873: Elements of the integer compositions sub-operad Comp of TN_2 generated by 00 and 010.
; Submitted by Penguin
; 1,11,12,111,112,121,122,1111,1112,1121,1122,1211,1212,1221,1222,11111,11112,11121,11122,11211,11212,11221,11222,12111,12112,12121,12122,12211,12212,12221,12222

mov $2,1
add $0,1
lpb $0
  mov $3,$0
  mod $3,2
  mul $3,$2
  div $0,2
  add $1,$3
  mul $2,10
lpe
mul $1,9
add $3,$1
mov $0,$3
div $0,9
