; A231875: Elements of the triassociative sub-operad Tri of TN generated by 01, 10 and 11.
; Submitted by Fornax
; 2,12,21,22,112,121,122,211,212,221,222,1112,1121,1122,1211,1212,1221,1222,2111,2112,2121,2122,2211,2212,2221,2222

seq $0,136724 ; Numbers divisible by 4 that are not powers of 2.
seq $0,284972 ; Numbers with digits 4 and 8 only.
div $0,400
