; A231873: Elements of the integer compositions sub-operad Comp of TN_2 generated by 00 and 010.
; Submitted by Jamie Morken(w1)
; 1,11,12,111,112,121,122,1111,1112,1121,1122,1211,1212,1221,1222,11111,11112,11121,11122,11211,11212,11221,11222,12111,12112,12121,12122,12211,12212,12221,12222

seq $0,132140 ; Numbers containing no zeros in ternary representation and with an initial 1.
seq $0,7089 ; Numbers in base 3.
