; A116080: Permutation of natural numbers generated by 4-rowed array shown below.
; Submitted by loader3229
; 0,4,1,8,5,2,12,9,6,3,16,13,10,7,20,17,14,11,24,21,18,15,28,25,22,19,32,29,26,23,36,33,30,27,40,37,34,31,44,41,38,35,48,45,42,39,52,49,46,43,56,53,50,47,60,57,54,51,64,61,58,55,68,65,62,59,72,69,66,63,76,73,70,67,80,77,74,71,84,81

#offset 1

mov $2,4
mov $3,1
mov $4,8
mov $5,5
mov $6,2
mov $7,12
mov $8,9
mov $9,6
mov $10,3
mov $11,16
sub $0,1
lpb $0
  sub $0,1
  mul $1,0
  mov $12,$1
  mov $1,$2
  mov $2,$3
  mov $3,$4
  mov $4,$5
  mov $5,$6
  mov $6,$7
  mul $7,-1
  add $12,$7
  add $12,$8
  add $12,$11
  mov $7,$8
  mov $8,$9
  mov $9,$10
  mov $10,$11
  mov $11,$12
lpe
mov $0,$1
