; A116547: Permutation of natural numbers generated by 5-rowed array shown below.
; Submitted by loader3229
; 0,5,1,10,6,2,15,11,7,3,20,16,12,8,4,25,21,17,13,9,30,26,22,18,14,35,31,27,23,19,40,36,32,28,24,45,41,37,33,29,50,46,42,38,34,55,51,47,43,39,60,56,52,48,44,65,61,57,53,49,70,66,62,58,54,75,71,67,63,59,80,76,72,68,64,85,81,77,73,69

#offset 1

mov $2,5
mov $3,1
mov $4,10
mov $5,6
mov $6,2
mov $7,15
mov $8,11
mov $9,7
mov $10,3
mov $11,20
mov $12,16
mov $13,12
mov $14,8
mov $15,4
mov $16,25
sub $0,1
lpb $0
  sub $0,1
  mul $1,0
  mov $17,$1
  mov $1,$2
  mov $2,$3
  mov $3,$4
  mov $4,$5
  mov $5,$6
  mov $6,$7
  mov $7,$8
  mov $8,$9
  mov $9,$10
  mov $10,$11
  mul $11,-1
  add $17,$11
  add $17,$12
  add $17,$16
  mov $11,$12
  mov $12,$13
  mov $13,$14
  mov $14,$15
  mov $15,$16
  mov $16,$17
lpe
mov $0,$1
