; A116468: Permutation of natural numbers generated by 2-rowed array shown below.
; Submitted by loader3229
; 2,3,1,6,4,7,5,10,8,11,9,14,12,15,13,18,16,19,17,22,20,23,21,26,24,27,25,30,28,31,29,34,32,35,33,38,36,39,37,42,40,43,41,46,44,47,45,50,48,51,49,54,52,55,53,58,56,59,57,62,60,63,61,66,64,67

#offset 1

mov $1,2
mov $2,3
mov $3,1
mov $4,6
mov $5,4
mov $6,7
sub $0,1
lpb $0
  mul $1,0
  rol $1,6
  sub $6,$1
  add $6,$2
  add $6,$5
  sub $0,1
lpe
mov $0,$1
