; A035877: Number of points of l_1 norm n in the "diamond" lattice D^+_2, i. e. the rectangular lattice generated by vectors (1, 1) and (-1/2, 1/2).
; Submitted by DukeBox
; 1,2,12,6,24,10,36,14,48,18,60,22,72,26,84,30,96,34,108,38,120,42,132,46,144,50,156,54,168,58,180,62,192,66,204,70,216,74,228,78,240,82,252,86,264,90,276,94,288,98,300,102,312,106,324,110,336,114,348,118,360,122,372,126,384,130,396,134,408,138,420,142,432,146,444,150,456,154,468,158
; Formula: a(n) = floor(((2*n+binomial(0,n))*gcd(binomial(0,n)+n,2)^2+gcd(binomial(0,n)+n,2)*(2*n+binomial(0,n)))/2)

bin $2,$0
add $2,$0
add $0,$2
gcd $2,2
mul $0,$2
mov $1,$2
mul $1,$0
add $1,$0
mov $0,$1
div $0,2
