; A290884: Let S be the sequence generated by these rules: 0 is in S, and if z is in S, then z * (1+i) and (z-1) * (1+i) + 1 are in S (where i denotes the imaginary unit), and duplicates are deleted as they occur; a(n) = the real part of the n-th term of S.
; Submitted by Jamie Morken(w1)
; 0,0,1,1,2,2,3,3,2,2,3,3,4,4,5,5,0,0,1,1,2,2,3,3,2,2,3,3,4,4,5,5,-4,-4,-3,-3,-2,-2,-1,-1,-2,-2,-1,-1,0,0,1,1,-4,-4,-3,-3,-2,-2,-1,-1,-2,-2,-1,-1,0,0,1,1,-8,-8,-7,-7,-6,-6,-5,-5,-6,-6,-5,-5,-4,-4,-3,-3,-8,-8,-7,-7,-6,-6,-5,-5,-6,-6,-5,-5,-4,-4,-3,-3,-12,-12,-11,-11

mov $4,1
lpb $0
  mov $2,$0
  mul $2,2
  mod $2,4
  sub $4,$3
  mul $3,2
  div $0,2
  mul $2,$3
  add $1,$2
  add $3,$4
lpe
mov $0,$1
div $0,4
