; A290885: Let S be the sequence generated by these rules: 0 is in S, and if z is in S, then z * (1+i) and (z-1) * (1+i) + 1 are in S (where i denotes the imaginary unit), and duplicates are deleted as they occur; a(n) = the imaginary part of the n-th term of S.
; Submitted by Jamie Morken(w1)
; 0,-1,-1,-2,0,-1,-1,-2,2,1,1,0,2,1,1,0,4,3,3,2,4,3,3,2,6,5,5,4,6,5,5,4,4,3,3,2,4,3,3,2,6,5,5,4,6,5,5,4,8,7,7,6,8,7,7,6,10,9,9,8,10,9,9,8,0,-1,-1,-2,0,-1,-1,-2,2,1,1,0,2,1,1,0

#offset 1

mov $3,-1
sub $0,1
lpb $0
  mov $2,$0
  mul $2,2
  mod $2,4
  sub $4,$3
  mul $3,2
  div $0,2
  mul $2,$3
  add $1,$2
  add $3,$4
lpe
mov $0,$1
div $0,4
