; A290886: Let S be the sequence generated by these rules: 0 is in S, and if z is in S, then z * (1+i) and (z-1) * (1+i) + 1 are in S (where i denotes the imaginary unit), and duplicates are deleted as they occur; a(n) = the square of the norm of the n-th term of S.
; Submitted by loader3229
; 0,1,2,5,4,5,10,13,8,5,10,9,20,17,26,25,16,9,10,5,20,13,18,13,40,29,34,25,52,41,50,41,32,25,18,13,20,13,10,5,40,29,26,17,36,25,26,17,80,65,58,45,68,53,50,37,104,85,82,65,100,81,82,65,64,65,50,53,36,37,26,29,40,37,26,25,20,17,10,9
; Formula: a(n) = A290884(n)^2+A290885(n)^2

#offset 1

mov $1,$0
seq $0,290884 ; Let S be the sequence generated by these rules: 0 is in S, and if z is in S, then z * (1+i) and (z-1) * (1+i) + 1 are in S (where i denotes the imaginary unit), and duplicates are deleted as they occur; a(n) = the real part of the n-th term of S.
pow $0,2
seq $1,290885 ; Let S be the sequence generated by these rules: 0 is in S, and if z is in S, then z * (1+i) and (z-1) * (1+i) + 1 are in S (where i denotes the imaginary unit), and duplicates are deleted as they occur; a(n) = the imaginary part of the n-th term of S.
pow $1,2
add $0,$1
