; A118588: Triangle generated by e.g.f.: A(x,y) = exp(x + y*(x^2+x^3)), read by rows of length [n/2+1].
; Submitted by Science United
; 1,1,1,2,1,12,1,36,12,1,80,180,1,150,1260,120,1,252,5460,3360,1,392,17640,43680,1680,1,576,46872,342720,75600,1,810,108360,1839600,1587600,30240,1,1100,225720,7539840,20235600,1995840,1,1452,433620,25391520
; Formula: a(n) = A342088(binomial(-n+floor((sqrtint(4*n+1)^2)/4)+sqrtint(4*n+1)-1,2)+sqrtint(4*n+1)-1)*binomial(-binomial(truncate((sqrtint(8*binomial(-n+floor((sqrtint(4*n+1)^2)/4)+sqrtint(4*n+1)-1,2)+8*sqrtint(4*n+1))-1)/2),2)+binomial(-n+floor((sqrtint(4*n+1)^2)/4)+sqrtint(4*n+1)-1,2)+sqrtint(4*n+1)-1,truncate((sqrtint(8*binomial(-n+floor((sqrtint(4*n+1)^2)/4)+sqrtint(4*n+1)-1,2)+8*sqrtint(4*n+1))-1)/2))

add $0,1
mov $3,$0
mul $0,4
sub $0,3
nrt $0,2
mov $2,$0
pow $2,2
div $2,4
sub $3,$2
mov $2,$3
mov $3,$0
sub $3,$2
bin $3,2
add $3,$0
mov $4,$3
mul $4,8
nrt $4,2
sub $4,1
div $4,2
mov $5,$4
bin $5,2
mov $1,$3
sub $1,1
sub $1,$5
bin $1,$4
mov $0,$3
sub $0,1
seq $0,342088 ; Triangle read by rows: T(n,k) is the number of n-colorings of the vertices of the k-dimensional cross polytope such that no two adjacent vertices have the same color. 0 <= k <= n.
mul $0,$1
