; A118588: Triangle generated by e.g.f.: A(x,y) = exp(x + y*(x^2+x^3)), read by rows of length [n/2+1].
; Submitted by Science United
; 1,1,1,2,1,12,1,36,12,1,80,180,1,150,1260,120,1,252,5460,3360,1,392,17640,43680,1680,1,576,46872,342720,75600,1,810,108360,1839600,1587600,30240,1,1100,225720,7539840,20235600,1995840,1,1452,433620,25391520
; Formula: a(n) = A342088(A056536(n+1)-1)*A046899(A056536(n+1)-1)

add $0,1
seq $0,56536 ; Mapping from half-antidiagonal reading of the triangle (as used in A028297) to the column-by-column reading of the triangular tables.
sub $0,1
mov $1,$0
seq $1,46899 ; Triangle in which n-th row is {binomial(n+k,k), k=0..n}, n >= 0.
seq $0,342088 ; Triangle read by rows: T(n,k) is the number of n-colorings of the vertices of the k-dimensional cross polytope such that no two adjacent vertices have the same color. 0 <= k <= n.
mul $0,$1
