; A119408: Decimal equivalent of the binary string generated by the n X n identity matrix.
; 1,9,273,33825,17043521,34630287489,282578800148737,9241421688590303745,1210107565283851686118401,634134936313486520338360567809

add $0,2
mov $2,$0
lpb $0
  mov $3,$0
  cmp $3,2
  add $0,$3
  sub $0,1
  add $4,1
  mov $5,2
  pow $5,$2
  mul $4,$5
lpe
mov $0,$4
add $0,1
