; A119486: Numbers of children for which there is a subset which cannot be generated by a counting-out game.
; Submitted by Skillz
; 9,12,15,18,20,21,24,25,27,28,30,33

mov $1,2
mov $2,$0
add $2,7
pow $2,2
lpb $2
  add $1,57
  mov $3,$1
  seq $3,86831 ; Ramanujan sum c_n(2).
  cmp $3,0
  sub $0,$3
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  sub $2,1
lpe
mov $0,$1
sub $0,59
div $0,57
add $0,9
