; A119485: Number of children for which any subset can be generated by a counting-out game.
; Submitted by kotenok2000
; 1,2,3,4,5,6,7,8,10,11,13,14,16,17,19,22,23,26,29,31,32

#offset 1

sub $0,1
mov $2,$0
pow $2,2
lpb $2
  mov $3,$1
  mov $5,$1
  add $5,8
  seq $5,5 ; d(n) (also called tau(n) or sigma_0(n)), the number of divisors of n.
  add $1,7
  add $3,8
  seq $3,10 ; Euler totient function phi(n): count numbers <= n and prime to n.
  add $5,$3
  mov $3,$5
  mul $3,2
  sub $3,$1
  trn $3,3
  min $3,1
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  equ $4,$0
  mul $2,$4
  sub $2,1
lpe
mov $0,$1
div $0,8
add $0,1
