; A119485: Number of children for which any subset can be generated by a counting-out game.
; Submitted by kotenok2000
; 1,2,3,4,5,6,7,8,10,11,13,14,16,17,19,22,23,26,29,31,32

mov $2,$0
pow $2,2
lpb $2
  add $1,7
  mov $3,$1
  seq $3,83245 ; Difference between numbers of related and numbers of unrelated numbers belonging to n: a(n) = A073757(n)-A045763(n) = (n-u(n))-u(n) = n-2*A045763(n) = 2*A073757(n)-n.
  mul $3,2
  trn $3,3
  min $3,1
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  sub $2,1
lpe
mov $0,$1
div $0,8
add $0,1
