; A119486: Numbers of children for which there is a subset which cannot be generated by a counting-out game.
; Submitted by mikey
; 9,12,15,18,20,21,24,25,27,28,30,33

mov $1,64
mov $2,$0
add $2,7
pow $2,2
lpb $2
  add $1,7
  mov $3,$1
  seq $3,83245 ; Difference between numbers of related and numbers of unrelated numbers belonging to n: a(n) = A073757(n)-A045763(n) = (n-u(n))-u(n) = n-2*A045763(n) = 2*A073757(n)-n.
  mul $3,-4
  trn $3,3
  min $3,1
  sub $0,$3
  add $1,1
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  sub $2,1
lpe
mov $0,$1
add $0,8
div $0,8
