; A119486: Numbers of children for which there is a subset which cannot be generated by a counting-out game.
; Submitted by yasiwo
; 9,12,15,18,20,21,24,25,27,28,30,33

#offset 1

mov $1,6
mov $2,$0
add $2,4
pow $2,2
lpb $2
  mov $3,$1
  mov $5,0
  add $1,2
  add $3,8
  lpb $3
    gcd $5,3
    mov $6,$3
    lpb $6
      mov $4,$3
      mod $4,$5
      add $5,2
      sub $6,$4
    lpe
    div $3,$5
    pow $3,2
    mov $5,1
  lpe
  add $0,$5
  sub $0,1
  sub $2,$0
lpe
mov $0,$1
div $0,2
add $0,4
