; A138017: Sequence generated by incidence matrix of the Fano plane, PG(2,2).
; Submitted by Jon Maiga
; 1,3,5,15,37,111,317,951,2821,8463,25325,75975,227797,683391,2049917,6149751,18448741,55346223

mov $2,4
add $0,1
lpb $0
  sub $0,1
  trn $1,4
  add $3,$2
  add $3,$4
  mov $2,$1
  add $1,$4
  add $4,$1
  mov $1,$3
  mul $2,3
  add $2,1
lpe
mov $0,$1
mul $0,2
sub $0,7
