; A082507: Generated by a 3rd-order formal recursion with suitable initial values as follows: a(n) = n - a(n-1) - a(n-2) - a(n-3); a(0)=a(1)=a(2)=0.
; Submitted by loader3229
; 2,0,0,0,3,1,1,1,4,2,2,2,5,3,3,3,6,4,4,4,7,5,5,5,8,6,6,6,9,7,7,7,10,8,8,8,11,9,9,9,12,10,10,10,13,11,11,11,14,12,12,12,15,13,13,13,16,14,14,14,17,15,15,15,18,16,16,16,19,17,17,17,20,18,18
; Formula: a(n) = 2*(((n+1)%4)==0)+floor((n+1)/4)

#offset -1

add $0,1
mov $2,$0
div $2,4
mod $0,4
mov $1,$0
equ $1,0
mul $1,2
add $2,$1
mov $0,$2
