; A332823: A 3-way classification indicator generated by the products of two consecutive primes and the cubes of primes. a(n) is -1, 0, or 1 such that a(n) == A048675(n) (mod 3).
; Submitted by [SG]KidDoesCrunch
; 0,1,-1,-1,1,0,-1,0,1,-1,1,1,-1,0,0,1,1,-1,-1,0,1,-1,1,-1,-1,0,0,1,-1,1,1,-1,0,-1,0,0,-1,0,1,1,1,-1,-1,0,-1,-1,1,0,1,0,0,1,-1,1,-1,-1,1,0,1,-1,-1,-1,0,0,0,1,1,0,0,1,-1,1,1,0,1,1,0,-1,-1,-1,-1,-1,1,0,-1,0,1,1,-1,0,1,0,0,-1,0,1,1,-1,-1,1

seq $0,195017 ; If n = Product_{k >= 1} (p_k)^(c_k) where p_k is k-th prime and c_k >= 0 then a(n) = Sum_{k >= 1} c_k*((-1)^(k-1)).
mod $0,3
dif $0,-2
