; A332823: A 3-way classification indicator generated by the products of two consecutive primes and the cubes of primes. a(n) is -1, 0, or 1 such that a(n) == A048675(n) (mod 3).
; Submitted by Drago75
; 0,1,-1,-1,1,0,-1,0,1,-1,1,1,-1,0,0,1,1,-1,-1,0,1,-1,1,-1,-1,0,0,1,-1,1,1,-1,0,-1,0,0,-1,0,1,1,1,-1,-1,0,-1,-1,1,0,1,0,0,1,-1,1,-1,-1,1,0,1,-1,-1,-1,0,0,0,1,1,0,0,1,-1,1,1,0,1,1,0,-1,-1,-1

seq $0,48675 ; If n = p_i^e_i * ... * p_k^e_k, p_i < ... < p_k primes (with p_i = prime(i)), then a(n) = (1/2) * (e_i * 2^i + ... + e_k * 2^k).
mod $0,-3
mov $1,$0
lpb $1
  mov $1,1
  lpb $0
    div $0,2
  lpe
  sub $0,1
lpe
