; A115731: Permutation of natural numbers generated by 3-rowed array shown below.
; Submitted by loader3229
; 1,6,2,7,5,3,12,8,4,13,11,9,18,14,10,19,17,15,24,20,16,25,23,21,30,26,22,31,29,27,36,32,28,37,35,33,42,38,34,43,41,39,48,44,40,49,47,45,54,50,46,55,53,51,60,56,52,61,59,57,66,62,58,67,65,63,72,68,64,73,71,69,78,74,70,79,77,75,84,80

#offset 1

mov $1,1
mov $2,6
mov $3,2
mov $4,7
mov $5,5
mov $6,3
mov $7,12
mov $8,8
mov $9,4
sub $0,1
lpb $0
  mul $1,0
  rol $1,9
  sub $9,$3
  add $9,$4
  add $9,$4
  sub $9,$5
  sub $9,$5
  add $9,$6
  add $9,$6
  sub $9,$7
  sub $9,$7
  add $9,$8
  add $9,$8
  sub $0,1
lpe
mov $0,$1
