; A115731: Permutation of natural numbers generated by 3-rowed array shown below.
; Submitted by jmorken
; 1,6,2,7,5,3,12,8,4,13,11,9,18,14,10,19,17,15,24,20,16,25,23,21,30,26,22,31,29,27,36,32,28,37,35,33,42,38,34,43,41,39,48,44,40,49,47,45,54,50,46,55,53,51,60,56,52,61,59,57,66,62,58,67,65,63,72,68,64,73,71,69,78,74,70,79,77,75,84,80

#offset 1

mov $3,1
mov $4,3
sub $0,1
mul $0,2
lpb $0
  sub $0,1
  add $3,3
  mov $2,$3
  sub $2,$0
  trn $0,$4
  mov $4,5
lpe
mov $0,$2
add $0,5
mov $1,$0
mul $1,15
dif $1,6
sub $1,2
mod $1,3
mul $1,2
sub $0,$1
sub $0,2
