; A007952: Generated by a sieve: keep first number, drop every 2nd, keep first, drop every 3rd, keep first, drop every 4th, etc.
; 0,1,3,5,9,11,17,21,29,33,41,47,57,59,77,81,101,107,117,131,149,153,173,191,209,213,239,257,273,281,321,329,359,371,401,417,441,453,497,509,539,569,611,621,647,671,717,731,779,801,839,869,917,929,989,1001,1053,1067

mov $2,$0
lpb $2,1
  mov $4,1
  add $4,$1
  lpb $4,1
    add $1,1
    sub $4,$2
  lpe
  sub $2,1
lpe
