; A069760: Frobenius number of the numerical semigroup generated by consecutive centered square numbers.
; 47,287,959,2399,5039,9407,16127,25919,39599,58079,82367,113567,152879,201599,261119,332927,418607,519839,638399,776159,935087,1117247,1324799,1559999,1825199,2122847

add $0,2
add $0,$0
mov $2,$0
lpb $0,1
  lpb $0,1
    add $4,$2
    sub $0,1
  lpe
  lpb $4,1
    sub $4,4
    add $3,$4
    add $1,$4
    add $1,$3
    sub $3,$3
  lpe
  sub $1,3
lpe
sub $1,5
add $1,7
