; A232867: Positions of the negative integers in the sequence (or tree) of complex numbers generated by these rules: 0 is in S, and if x is in S, then x + 1 and i*x are in S, where duplicates are deleted as they occur.
; 8,12,19,30,45,64,87,114,145,180,219,262,309,360,415,474,537,604,675,750,829,912,999,1090,1185,1284,1387,1494,1605,1720,1839,1962,2089,2220,2355,2494,2637,2784,2935,3090,3249,3412,3579,3750,3925,4104,4287,4474

mov $4,4
mov $1,4
add $0,$0
lpb $0,1
  add $1,$0
  mov $2,1
  sub $0,1
lpe
add $1,$2
add $1,$4
