; A232866: Positions of the nonnegative integers in the sequence (or tree) of complex numbers generated by these rules: 0 is in S, and if x is in S, then x + 1 and i*x are in S, where duplicates are deleted as they occur.
; 1,2,3,5,9,16,27,42,61,84,111,142,177,216,259,306,357,412,471,534,601,672,747,826,909,996,1087,1182,1281,1384,1491,1602,1717,1836,1959,2086,2217,2352,2491,2634,2781,2932,3087,3246,3409,3576,3747,3922,4101,4284

lpb $0,1
  add $4,1
  add $2,$3
  sub $2,5
  mov $3,$0
  add $5,$0
  sub $5,2
  sub $0,1
  sub $3,4
  add $5,$3
  add $4,$5
  mov $5,$3
  add $4,$2
  mov $2,$0
  sub $2,$5
  mov $3,$2
  mov $2,$0
  sub $5,1
lpe
mov $1,$4
add $1,1
