; A267922: Triangle read by rows giving successive states of cellular automaton generated by "Rule 245" initiated with a single ON (black) cell.
; 1,0,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1

lpb $0,1
  mov $6,4
  add $4,2
  mov $2,$0
  add $2,2
  sub $6,$2
  mov $5,$6
  mov $3,$1
  sub $0,3
  mov $2,$1
  sub $0,$4
lpe
add $1,2
add $6,1
add $1,$1
add $6,2
sub $1,$6
