; A105392: Frobenius number of the subsemigroup of the natural numbers generated by successive pairs of Lucas numbers.
; Submitted by KetamiNO [YouTube]
; 0,5,17,59,169,475,1287,3449,9149,24155,63557,166919,437839,1147645,3006777,7875419,20623889,54003395,141397847,370208849,969258949,2537616955,6643671117,17393524559,45537109919,119218140725
; Formula: a(n) = c(n)*b(n)-1, b(n) = b(n-1)+c(n-1)+1, b(1) = 1, b(0) = 0, c(n) = max(c(n-1)+1,b(n-1)), c(1) = 1, c(0) = 0

#offset 1

lpb $0
  sub $0,1
  add $2,1
  mov $3,$2
  max $2,$1
  add $1,$3
lpe
mov $0,$2
mul $0,$1
sub $0,1
