; A105392: Frobenius number of the subsemigroup of the natural numbers generated by successive pairs of Lucas numbers.
; Submitted by loader3229
; 0,5,17,59,169,475,1287,3449,9149,24155,63557,166919,437839,1147645,3006777,7875419,20623889,54003395,141397847,370208849,969258949,2537616955,6643671117,17393524559,45537109919,119218140725

#offset 1

mov $2,5
mov $3,17
mov $4,59
mov $5,169
mov $6,475
sub $0,1
lpb $0
  mul $1,0
  rol $1,6
  add $6,$1
  sub $6,$2
  mov $7,$3
  mul $7,-5
  add $6,$7
  add $6,$4
  mov $7,$5
  mul $7,3
  sub $0,1
  add $6,$7
lpe
mov $0,$1
