; A049539: Number of distinct binary sequences of length k+n generated by a general (non-linear) binary feedback shift register of length k, for sufficiently large k.
; Submitted by [SG-FC] hl
; 1,4,14,43,125,340,896,2281,5672,13807

mov $3,$0
mov $2,$0
add $2,1
lpb $2
  sub $2,1
  mov $0,$3
  sub $0,$2
  seq $0,59412 ; Number of distinct minimal unary DFA's with exactly n states.
  mul $1,2
  add $1,$0
lpe
mov $0,$1
sub $0,2
div $0,2
add $0,1
