; A181656: Generalized (conditional) Riordan array with k-th column generated by x^k*(1+x^2) if k mod 2 = 0, x^k*(1+x) otherwise.
; Submitted by Jon Maiga
; 1,0,1,1,1,1,0,0,0,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1

lpb $0
  add $1,1
  sub $0,$1
  mov $2,$1
  sub $2,$0
lpe
gcd $0,2
bin $0,$2
mod $0,2
