; A181653: Generalized (conditional) Riordan array with k-th column generated by x^k*(1+x) if k mod 2 = 0, x^k*(1+x+x^2) otherwise.
; Submitted by emoga
; 1,1,1,0,1,1,0,1,1,1,0,0,0,1,1,0,0,0,1,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,1

lpb $0
  add $2,1
  sub $0,$2
lpe
add $0,1
mov $1,$2
bin $1,$0
max $1,1
sub $2,$0
mov $0,$2
lpb $0
  sub $0,1
  mul $1,$2
  sub $2,1
lpe
mov $0,$1
mod $0,2
