; A181533: Number of values generated by the algorithm given as first comment.
; Submitted by loader3229
; 2,4,8,8,12,34,58,96,188,334,574,1046,1874,3308,5928,10608,18872,33694,60194,107338,191542,341950,610146,1088790,1943262,3467858,6188534,11044356,19709736,35173564,62771096,112021424,199912600,356764214,636681638,1136220266,2027697682

#offset 1

mov $1,2
mov $2,4
mov $3,8
mov $4,8
mov $5,12
mov $6,34
mov $7,58
mov $8,96
mov $9,188
mov $10,334
sub $0,1
lpb $0
  sub $0,1
  mov $11,$1
  mov $1,$2
  mov $2,$3
  mul $3,-2
  add $11,$3
  mov $3,$4
  mov $4,$5
  mul $5,3
  add $11,$5
  mov $5,$6
  mov $6,$7
  mul $7,-2
  add $11,$7
  mov $7,$8
  mov $8,$9
  mov $9,$10
  mul $10,2
  add $11,$10
  mov $10,$11
lpe
mov $0,$1
