; A278959: Length of the string that is generated by the concatenation of all the prime numbers < n (where n >= 0).
; 0,0,0,1,2,2,3,3,4,4,4,4,6,6,8,8,8,8,10,10,12,12,12,12,14,14,14,14,14,14,16,16,18,18,18,18,18,18,20,20,20,20,22,22,24,24,24,24,26,26,26,26,26,26,28,28,28,28,28,28,30

sub $0,1
cal $0,230980
add $3,$0
mov $2,$0
sub $3,10
mov $3,$2
mov $0,$2
lpb $2,1
  mov $1,$2
  mov $26,$2
  cmp $26,0
  add $2,$26
  div $1,$2
  add $1,236840
  sub $3,2
  mov $2,4
  add $1,$0
  add $5,$0
  mov $1,9
  mul $3,2
  pow $5,2
  pow $5,2
  mov $5,$1
lpe
lpb $2,1
  sub $5,2
  mov $3,4
  lpb $1,3
    sub $5,1
    mod $1,2
    add $0,$1
    add $5,$5
    mov $4,2
  lpe
  mul $2,$5
  div $1,2
lpe
mul $5,$5
mov $1,$0
mov $1,$3
