; A082507: Generated by a 3rd-order formal recursion with suitable initial values as follows: a(n) = n - a(n-1) - a(n-2) - a(n-3); a(0)=a(1)=a(2)=0.
; 2,0,0,0,3,1,1,1,4,2,2,2,5,3,3,3,6,4,4,4,7,5,5,5,8,6,6,6,9,7,7,7,10,8,8,8,11,9,9,9,12,10,10,10

mov $2,$0
mov $0,3
add $2,1
lpb $2,1
  trn $1,1
  add $1,4
  sub $2,$3
  sub $1,2
  trn $3,$2
  lpb $3,1
    mov $3,2
    sub $1,$0
  lpe
  mov $3,$0
  trn $2,1
lpe
