; A082507: Generated by a 3rd-order formal recursion with suitable initial values as follows: a(n) = n - a(n-1) - a(n-2) - a(n-3); a(0)=a(1)=a(2)=0.
; 2,0,0,0,3,1,1,1,4,2,2,2,5,3,3,3,6,4,4,4,7,5,5,5,8,6,6,6,9,7,7,7,10,8,8,8,11,9,9,9,12,10,10,10

add $0,100
mov $2,100
lpb $2
  sub $0,1
  mov $1,$2
  add $2,$0
  div $2,5
lpe
sub $1,25
