; A263243: Triangle read by rows giving successive states of cellular automaton generated by "Rule 155" initiated with a single ON (black) cell.
; Submitted by gingavasalata
; 1,1,0,1,1,0,0,1,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

mov $2,1
lpb $0
  add $2,2
  sub $0,$2
lpe
mov $1,1
mov $3,1
sub $0,1
lpb $0
  sub $0,1
  pow $0,2
  mul $1,$2
  add $1,$3
  dif $1,2
  mov $4,$3
  add $3,$1
lpe
mov $0,$4
add $0,1
mod $0,2
