; A263919: Triangle read by rows giving successive states of cellular automaton generated by "Rule 163" initiated with a single ON (black) cell.
; Submitted by AlexxAl
; 1,1,0,0,1,0,0,1,0,1,0,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0

lpb $0
  add $1,1
  sub $0,$1
  add $1,1
lpe
sub $1,$0
div $0,2
add $0,1
lpb $0
  sub $0,1
  mul $0,2
  add $1,1
lpe
mov $0,$1
mod $0,2
