; A226136: Positions of the positive integers in the ordering of rational numbers as generated by the rules: 1 is in S, and if nonzero x is in S, then x+1 and -1/x are in S.  (See Comments).
; 1,2,4,7,10,15,22,32,47,69,101,148,217,318,466,683,1001,1467,2150,3151,4618,6768,9919,14537,21305,31224,45761,67066,98290,144051,211117,309407,453458,664575,973982,1427440

mov $4,$0
add $4,1
mov $6,$0
lpb $4,1
  mov $0,$6
  sub $4,1
  sub $0,$4
  mov $2,$0
  cmp $2,0
  add $0,$2
  sub $0,1
  cal $0,226275
  mov $3,$0
  mov $1,$3
  add $5,$1
lpe
mov $1,$5
