; A137617: Decimal expansion of volume of the solid of revolution generated by a Reuleaux triangle rotated around one of its symmetry axes.
; Submitted by arkiss
; 4,4,9,4,6,1,0,3,5,5,4,4,9,6,9,0,5,5,8,3,6,0,1,3,7,5,5,5,4,0,3,1,0,0,6,6,9,1,2,4,9,6,3,6,5,0,4,3,2,7,2,1,0,9,5,8,1,0,7,1,4,9,8,8,3,5,2,0,3,4,6,7,1,2,0,9,3,8,4,5

add $0,1
mov $1,1
mov $3,$0
mul $3,7
lpb $3
  max $3,1
  max $6,$2
  div $6,$3
  sub $7,$4
  add $2,$1
  sub $3,1
  equ $4,$6
  add $4,$1
  add $4,$7
  mul $7,2
  mul $1,2
  add $1,$6
lpe
mov $4,10
pow $4,$0
sub $5,$2
pow $5,2
mul $5,2
bin $2,2
sub $2,$5
div $2,$4
mul $1,$7
div $1,2
div $1,$2
mov $0,$1
mod $0,10
