; A137618: Decimal expansion of surface area of the solid of revolution generated by a Reuleaux triangle rotated around one of its symmetry axes.
; Submitted by Mumps
; 2,9,9,3,3,1,7,1,7,3,4,8,3,1,3,3,6,0,3,9,8,0,4,5,6,4,3,3,2,6,6,9,5,5,3,8,9,9,5,6,4,3,8,9,9,6,3,3,6,6,1,4,7,6,6,4,7,8,7,7,2,7,2,5,8,7,5,6,1,7,8,7,1,7,6,6,0,1,6,2

#offset 1

mov $1,1
mov $3,$0
mul $3,7
lpb $3
  max $3,1
  add $4,$1
  max $6,$2
  div $6,$3
  sub $7,$4
  add $2,$1
  sub $3,1
  equ $4,$6
  add $4,$1
  add $4,$7
  mul $7,2
  mul $1,2
  add $1,$6
lpe
mov $4,10
pow $4,$0
sub $5,$2
mul $5,2
pow $5,2
mul $5,2
bin $2,2
sub $2,$5
div $2,$4
mul $1,$7
div $1,2
div $1,$2
mov $0,$1
mod $0,10
