; A365679: a(n) is the number of exterior top arches (no covering arch) for semi-meanders in generation n+1 that are generated by semi-meanders with n top arches and floor((n+2)/2) exterior top arches using the exterior arch splitting algorithm.
; Submitted by tomkalei
; 4,10,14,32,40,88,104,224,256,544,608,1280,1408,2944,3200,6656,7168,14848,15872,32768,34816,71680,75776,155648,163840,335872,352256,720896,753664,1540096,1605632,3276800,3407872,6946816,7208960,14680064
; Formula: a(n) = (2*n-floor((n+1)/2)+4)*2^floor((n+1)/2)

mov $1,$0
mul $0,2
add $0,4
add $1,1
div $1,2
mov $2,2
pow $2,$1
sub $0,$1
mul $0,$2
