; A365679: a(n) is the number of exterior top arches (no covering arch) for semi-meanders in generation n+1 that are generated by semi-meanders with n top arches and floor((n+2)/2) exterior top arches using the exterior arch splitting algorithm.
; Submitted by crashtech
; 4,10,14,32,40,88,104,224,256,544,608,1280,1408,2944,3200,6656,7168,14848,15872,32768,34816,71680,75776,155648,163840,335872,352256,720896,753664,1540096,1605632,3276800,3407872,6946816,7208960,14680064
; Formula: a(n) = b(n+1)+d(n+1)+e(n+1), b(n) = b(n-1)*(c(n-1)+1), b(3) = 4, b(2) = 4, b(1) = 2, b(0) = 2, c(n) = -2*truncate((c(n-1)+1)/2)+c(n-1)+1, c(3) = 1, c(2) = 0, c(1) = 1, c(0) = 0, d(n) = d(n-1)*(c(n-1)+1)+b(n-1), d(3) = 10, d(2) = 6, d(1) = 2, d(0) = 0, e(n) = e(n-1), e(3) = 0, e(2) = 0, e(1) = 0, e(0) = 0

mov $2,2
mov $1,$0
add $1,1
lpb $1
  sub $1,1
  add $3,1
  mul $4,$3
  add $4,$2
  mul $2,$3
  mod $3,2
lpe
add $5,$4
add $2,$5
mov $0,$2
