; A266666: Triangle read by rows giving successive states of cellular automaton generated by "Rule 51" initiated with a single ON (black) cell.
; 1,1,0,1,0,0,1,0,0,1,1,1,0,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,0,1,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,1,1

cal $0,137735
add $2,2
mov $26,$2
cmp $26,0
add $2,$26
mod $0,$2
trn $2,4
mov $4,$2
mov $4,3
mov $1,2
pow $0,2
mov $1,$0
add $0,$4
mov $0,$1
mul $0,14
mov $2,$0
sub $1,$2
mov $1,$0
add $2,$1
mov $0,$2
add $2,2
sub $1,$0
mov $1,$4
mov $1,$0
div $1,28
