; A266659: Triangle read by rows giving successive states of cellular automaton generated by "Rule 47" initiated with a single ON (black) cell.
; 1,1,1,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1

mul $0,2
add $3,2
mov $2,$3
sub $0,$3
add $3,1
add $4,2
lpb $0,5
  mov $1,3
  add $2,3
  add $3,1
  mov $2,$0
  mov $2,$2
  add $1,97
  add $2,11
  add $1,$3
  sub $0,$3
  add $4,$2
  mov $0,$0
  trn $1,$1
lpe
add $0,$3
sub $2,$0
add $3,2
trn $1,$3
bin $2,2
add $4,1
sub $1,$0
mul $3,$2
mul $4,$4
mov $0,3
mul $2,2
add $4,1
lpb $0,1
  add $4,52
  pow $1,2
  lpb $3,2
    mod $3,8
    mov $0,1
    sub $4,$4
    mod $1,2
    sub $0,$4
    sub $4,1
  lpe
  add $2,1
  div $3,3
  add $1,$0
  add $4,$1
  div $3,7
lpe
sub $3,$0
sub $1,1
