; A301848: Number of states generated by morphism during inflation stage of paper-folding sequence.
; Submitted by Landjunge
; 1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,2,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,2,3,1,4

mov $1,$0
lpb $0
  dif $0,2
lpe
div $0,2
mod $0,2
add $0,1
mod $1,2
mul $1,2
add $0,$1
