; A301848: Number of states generated by morphism during inflation stage of paper-folding sequence.
; Submitted by Landjunge
; 1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,2,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,2,3,1,4

mov $1,$0
seq $0,38189 ; Bit to left of least significant 1-bit in binary expansion of n.
add $0,1
mod $1,2
mul $1,2
add $0,$1
