; A262855: Triangle read by rows giving successive states of cellular automaton generated by "Rule 153" initiated with a single ON (black) cell.
; Submitted by Simon Strandgaard
; 1,0,0,1,0,1,0,1,1,0,0,0,0,1,1,1,0,1,1,1,0,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,0,1,0,1,0,1,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1

lpb $0
  sub $0,$1
  add $1,1
  sub $0,$1
  mov $2,1
lpe
bin $1,$0
add $2,$1
mov $0,$2
mod $0,2
