; A262855: Triangle read by rows giving successive states of cellular automaton generated by "Rule 153" initiated with a single ON (black) cell.
; Submitted by loader3229
; 1,0,0,1,0,1,0,1,1,0,0,0,0,1,1,1,0,1,1,1,0,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,0,1,0,1,0,1,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
; Formula: a(n) = -2*truncate((binomial(sqrtint(n+1),-sqrtint(n+1)^2+n)+1)/2)+binomial(sqrtint(n+1),-sqrtint(n+1)^2+n)+1

add $0,1
mov $1,$0
nrt $0,2
mov $2,$0
pow $2,2
add $2,1
sub $1,$2
bin $0,$1
add $0,1
mod $0,2
