; A326790: The rank of the group of functions on the units of Z/nZ generated by the functions f(u) = u*k mod n.
; 0,1,2,2,3,2,4,3,4,3,6,3,7,4,5,5,9,4,10,5,7,6,12,5,11,7,10,7,15,5,16,9,11,9,13,7,19,10,13,9,21,7,22,11,13,12,24,9,22,11,17,13,27,10,21,13,19,15,30,9,31,16,19,17,25,11,34,17,23

mov $4,5
lpb $0
  mov $3,$0
  mov $0,4
  mov $1,2
  cal $3,10 ; Euler totient function phi(n): count numbers <= n and prime to n.
  add $2,$3
  sub $4,1
  sub $0,$4
  div $2,2
  mul $2,2
  add $1,$2
lpe
div $1,2
