; A266377: Triangle read by rows giving successive states of cellular automaton generated by "Rule 21" initiated with a single ON (black) cell.
; Submitted by Torbj&#246;rn Eriksson
; 1,0,1,1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

mov $1,$0
nrt $1,2
lpb $0
  mov $0,1
  mov $2,-1
lpe
add $1,$2
mov $0,$1
add $0,1
mod $0,2
