; A266253: Triangle read by rows giving successive states of cellular automaton generated by "Rule 11" initiated with a single ON (black) cell.
; Submitted by USTL-FIL (Lille Fr)
; 1,1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0

mov $2,1
mov $3,1
mov $1,$0
add $1,2
lpb $1
  sub $1,$3
  add $3,2
  add $2,$3
lpe
mov $0,$2
sub $0,1
mod $0,2
