; A266982: Triangle read by rows giving successive states of cellular automaton generated by "Rule 81" initiated with a single ON (black) cell.
; Submitted by Skillz
; 1,0,0,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

add $0,1
mov $1,$0
sub $0,2
lpb $0
  trn $0,1
  mov $1,2
  mov $2,$0
  nrt $2,2
  trn $0,1
  lpb $0
    div $0,5
  lpe
  add $1,$2
lpe
mov $0,$1
mod $0,2
