; A266282: Triangle read by rows giving successive states of cellular automaton generated by "Rule 13" initiated with a single ON (black) cell.
; Submitted by owensse
; 1,0,1,0,0,0,1,0,1,1,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,1,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0

mov $2,$0
lpb $0
  add $3,2
  mov $0,$2
  div $0,$3
  sub $0,$3
  mov $1,3
lpe
lpb $0
  mov $1,$0
  mul $1,$2
  div $0,4
lpe
add $1,1
mod $1,2
mov $0,$1
