; A266982: Triangle read by rows giving successive states of cellular automaton generated by "Rule 81" initiated with a single ON (black) cell.
; Submitted by Mumps
; 1,0,0,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

mov $4,$0
max $4,1
mov $1,$4
trn $4,2
nrt $4,2
mov $2,$0
add $2,$4
sub $3,$2
sub $3,$1
mov $0,$3
mod $0,2
add $0,2
mod $0,2
