; A266282: Triangle read by rows giving successive states of cellular automaton generated by "Rule 13" initiated with a single ON (black) cell.
; Submitted by Torbj&#246;rn Eriksson
; 1,0,1,0,0,0,1,0,1,1,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,1,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0
; Formula: a(n) = sqrtint(4*n+5)*(n+3)-floor((sqrtint(4*n+5)^2)/4)-2*truncate((sqrtint(4*n+5)*(n+3)-floor((sqrtint(4*n+5)^2)/4))/2)

mov $3,$0
add $3,3
mul $0,4
add $0,5
nrt $0,2
mov $2,$0
pow $2,2
div $2,4
sub $1,$2
mul $0,$3
add $0,$1
mod $0,2
