; A266666: Triangle read by rows giving successive states of cellular automaton generated by "Rule 51" initiated with a single ON (black) cell.
; Submitted by loader3229
; 1,1,0,1,0,0,1,0,0,1,1,1,0,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,0,1,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
; Formula: a(n) = (floor(gcd(n,sqrtint(n)+1)/(sqrtint(n)+1))+sqrtint(n)+2)%2

mov $1,$0
nrt $1,2
add $1,1
gcd $0,$1
div $0,$1
add $0,$1
add $0,1
mod $0,2
