; A266216: Triangle read by rows giving successive states of cellular automaton generated by "Rule 7" initiated with a single ON (black) cell.
; Submitted by [BOINC@Poland]emik
; 1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
; Formula: a(n) = max(((n-2)==1)+sqrtint(n),1)%2

mov $3,$0
sub $3,2
nrt $0,2
mov $1,$3
equ $1,1
mov $2,$0
add $2,$1
max $2,1
mov $0,$2
mod $0,2
