; A266282: Triangle read by rows giving successive states of cellular automaton generated by "Rule 13" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,0,1,0,0,0,1,0,1,1,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,1,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0
; Formula: a(n) = sqrtint(4*n+5)*(n+3)-floor((sqrtint(4*n+5)^2)/4)-2*truncate((sqrtint(4*n+5)*(n+3)-floor((sqrtint(4*n+5)^2)/4)-2)/2)-2

add $0,2
mov $1,$0
mov $3,$0
add $3,1
mul $0,4
sub $0,3
nrt $0,2
mov $2,$0
pow $2,2
div $2,4
add $2,$3
sub $1,$2
mul $0,$3
add $0,$1
sub $0,1
mod $0,2
