; A266659: Triangle read by rows giving successive states of cellular automaton generated by "Rule 47" initiated with a single ON (black) cell.
; Submitted by Rodney Duane
; 1,1,1,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
; Formula: a(n) = if(n==0,sqrtint(n+2),if((sqrtint(n+2)%n)==0,sqrtint(n+2)/n,sqrtint(n+2)))%2

mov $1,$0
add $0,2
nrt $0,2
dif $0,$1
mod $0,2
