; A267778: Triangle read by rows giving successive states of cellular automaton generated by "Rule 211" initiated with a single ON (black) cell.
; Submitted by Conan
; 1,1,0,1,1,1,0,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0
; Formula: a(n) = -gcd(sqrtint(n+1),2)-2*truncate((-gcd(sqrtint(n+1),2)+sqrtint(gcd(sqrtint(n+1),2)+n+1)+1)/2)+sqrtint(gcd(sqrtint(n+1),2)+n+1)+1

add $0,1
mov $1,$0
nrt $1,2
gcd $1,2
add $1,$0
sub $0,$1
nrt $1,2
add $0,$1
add $0,1
mod $0,2
