; A267673: Triangle read by rows giving successive states of cellular automaton generated by "Rule 195" initiated with a single ON (black) cell.
; Submitted by loader3229
; 1,1,0,0,1,1,0,1,0,1,1,1,0,0,0,0,1,1,1,1,0,1,1,1,0,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
; Formula: a(n) = -2*truncate((binomial(floor((sqrtint(4*n+12)-1)/2),-2*floor((floor((sqrtint(4*n+12)-1)/2)*(floor((sqrtint(4*n+12)-1)/2)+1))/2)+n)+1)/2)+binomial(floor((sqrtint(4*n+12)-1)/2),-2*floor((floor((sqrtint(4*n+12)-1)/2)*(floor((sqrtint(4*n+12)-1)/2)+1))/2)+n)+1

mov $2,$0
add $0,3
mul $0,4
nrt $0,2
sub $0,1
div $0,2
mov $1,$0
fac $1,2
div $1,2
sub $2,$1
sub $2,$1
bin $0,$2
add $0,1
mod $0,2
