; A267006: Triangle read by rows giving successive states of cellular automaton generated by "Rule 84" initiated with a single ON (black) cell.
; Submitted by Aexoden
; 1,0,1,1,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
; Formula: a(n) = -2*truncate(d(n+2)/2)+d(n+2), b(n) = truncate((-c(n-1)+b(n-1))/2)-2, b(2) = -13, b(1) = -6, b(0) = 0, c(n) = c(n-1)*(-2*truncate((d(n-1)+truncate((-c(n-1)+b(n-1))/2))/2)+d(n-1)+truncate((-c(n-1)+b(n-1))/2)+2), c(2) = 32, c(1) = 16, c(0) = 8, d(n) = -2*truncate((d(n-1)+truncate((-c(n-1)+b(n-1))/2))/2)+d(n-1)+truncate((-c(n-1)+b(n-1))/2)+3, d(2) = 3, d(1) = 3, d(0) = 0

mov $2,8
add $0,2
lpb $0
  sub $0,1
  sub $1,$2
  div $1,2
  add $3,$1
  mod $3,2
  add $3,2
  sub $1,2
  mul $2,$3
  add $3,1
lpe
mov $0,$3
mod $0,2
