; A267612: Triangle read by rows giving successive states of cellular automaton generated by "Rule 185" initiated with a single ON (black) cell.
; 1,0,0,1,0,1,0,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

mov $1,$0
lpb $1
  mov $0,16
  sub $1,1
  add $3,2
  sub $1,$3
  mov $2,2
lpe
lpb $0
  mov $0,$1
  pow $0,$2
lpe
add $0,1
mod $0,2
