; A267598: Triangle read by rows giving successive states of cellular automaton generated by "Rule 177" initiated with a single ON (black) cell.
; Submitted by Ralfy
; 1,0,0,1,0,1,0,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0
; Formula: a(n) = d(n+3)%2, b(n) = b(n-1)/2-b(n-1)+c(n-1), b(3) = 9, b(2) = 7, b(1) = 2, b(0) = 0, c(n) = gcd(b(n-1)/2,2)*(b(n-1)/2+2*c(n-1)-2*b(n-1)), c(3) = 15, c(2) = 13, c(1) = 8, c(0) = 2, d(n) = d(n-1)+gcd(b(n-2)/2,2), d(3) = 3, d(2) = 2, d(1) = 0, d(0) = 0

mov $2,2
add $0,3
lpb $0
  sub $0,1
  sub $2,$1
  add $4,$3
  div $1,2
  mov $3,$1
  gcd $3,2
  add $1,$2
  add $2,$1
  mul $2,$3
lpe
mov $0,$4
mod $0,2
