; A267869: Triangle read by rows giving successive states of cellular automaton generated by "Rule 235" initiated with a single ON (black) cell.
; Submitted by loader3229
; 1,1,0,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
; Formula: a(n) = if(if((bitxor(n,3)%5)==0,bitxor(n,3)/5,bitxor(n,3))==0,0,if((if((bitxor(n,3)%5)==0,bitxor(n,3)/5,bitxor(n,3))^2)<=1,0,valuation(if((bitxor(n,3)%5)==0,bitxor(n,3)/5,bitxor(n,3)),if((bitxor(n,3)%5)==0,bitxor(n,3)/5,bitxor(n,3)))))

bxo $0,3
dif $0,5
lex $0,$0
