; A267673: Triangle read by rows giving successive states of cellular automaton generated by "Rule 195" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,1,0,0,1,1,0,1,0,1,1,1,0,0,0,0,1,1,1,1,0,1,1,1,0,1,1,1,1,1,0,0,1,1,0,0,1,1,1,1,1,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
; Formula: a(n) = -2*truncate((binomial(sqrtint(4*max(n,1)+1),2*max(n,1)-2*floor((sqrtint(4*max(n,1)+1)^2)/4)+1)+1)/2)+binomial(sqrtint(4*max(n,1)+1),2*max(n,1)-2*floor((sqrtint(4*max(n,1)+1)^2)/4)+1)+1

max $0,1
add $0,1
mov $1,$0
mul $0,4
sub $0,3
nrt $0,2
mov $2,$0
pow $2,2
div $2,4
add $2,1
sub $1,$2
mul $1,2
mov $2,$1
add $2,1
bin $0,$2
add $0,1
mod $0,2
