; A267612: Triangle read by rows giving successive states of cellular automaton generated by "Rule 185" initiated with a single ON (black) cell.
; Submitted by Fardringle
; 1,0,0,1,0,1,0,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

mov $3,1
bin $1,$0
mov $2,$0
lpb $2
  add $3,2
  mov $1,3
  sub $2,$3
lpe
lpb $1
  mov $1,$2
  sub $1,1
lpe
mov $0,$1
mod $0,2
