; A267006: Triangle read by rows giving successive states of cellular automaton generated by "Rule 84" initiated with a single ON (black) cell.
; Submitted by Aexoden
; 1,0,1,1,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
; Formula: a(n) = d(n)%2, b(n) = (-c(n-1)+b(n-1))/2-2, b(2) = -30, b(1) = -24, b(0) = -13, c(n) = c(n-1)*(((-c(n-1)+b(n-1))/2+d(n-1))%2+2), c(2) = 64, c(1) = 32, c(0) = 32, d(n) = ((-c(n-1)+b(n-1))/2+d(n-1))%2+3, d(2) = 3, d(1) = 2, d(0) = 3

mov $2,8
add $0,2
lpb $0
  sub $0,1
  sub $1,$2
  div $1,2
  add $3,$1
  mod $3,2
  add $3,2
  sub $1,2
  mul $2,$3
  add $3,1
lpe
mov $0,$3
mod $0,2
