; A267813: Triangle read by rows giving successive states of cellular automaton generated by "Rule 219" initiated with a single ON (black) cell.
; Submitted by Skillz
; 1,1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1

mov $1,$0
mul $1,4
mov $3,$1
nrt $3,2
add $0,1
mul $0,4
mov $2,$0
nrt $2,2
mov $0,$2
mod $0,2
mov $1,$3
pow $1,$0
mov $0,$1
mod $0,2
