; A267594: Triangle read by rows giving successive states of cellular automaton generated by "Rule 173" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,0,1,0,0,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
; Formula: a(n) = -2*truncate((truncate(truncate((n-1)/((sqrtint(n)==0)+sqrtint(n)))/((sqrtint(n)==0)+sqrtint(n)))+2)/2)+truncate(truncate((n-1)/((sqrtint(n)==0)+sqrtint(n)))/((sqrtint(n)==0)+sqrtint(n)))+2

mov $1,$0
sub $1,1
mov $2,$0
nrt $2,2
mov $3,$2
equ $3,0
add $2,$3
div $1,$2
div $1,$2
mov $0,$1
add $0,2
mod $0,2
