; A267800: Triangle read by rows giving successive states of cellular automaton generated by "Rule 213" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,0,1,1,1,0,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1

mov $1,$0
add $1,3
add $0,1
mov $2,$0
lpb $2
  mov $2,1
  mov $3,$1
  nrt $3,2
  pow $3,2
  neq $3,$1
  add $1,1
  mul $2,$3
lpe
mov $0,$2
