; A267814: Triangle read by rows giving successive states of cellular automaton generated by "Rule 221" initiated with a single ON (black) cell.
; Submitted by Skillz
; 1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1

mov $1,$0
add $1,1
mov $3,$1
mul $3,4
mov $2,$3
nrt $2,2
mul $1,2
add $1,1
mul $1,2
mov $4,$1
nrt $4,2
sub $2,$4
mov $0,$2
add $0,1
