; A267635: Triangle read by rows giving successive states of cellular automaton generated by "Rule 189" initiated with a single ON (black) cell.
; Submitted by [SG]KidDoesCrunch
; 1,0,1,1,0,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
; Formula: a(n) = (sqrtint(n+2)^2)!=n

mov $1,$0
add $1,2
nrt $1,2
pow $1,2
neq $1,$0
mov $0,$1
