; A267927: Triangle read by rows giving successive states of cellular automaton generated by "Rule 249" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,0,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

mov $1,$0
pow $0,2
mov $2,$0
cmp $2,0
gcd $3,$1
add $0,$2
dif $0,3
add $0,1
div $0,2
cmp $0,$3
add $0,1
mod $0,2
