; A267813: Triangle read by rows giving successive states of cellular automaton generated by "Rule 219" initiated with a single ON (black) cell.
; Submitted by arkiss
; 1,1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1

mov $5,1
max $5,$0
mov $2,$5
add $2,1
mod $2,-2
mov $6,$5
mul $6,$2
div $6,2
lpb $6
  add $1,1
  sub $6,$1
lpe
add $6,1
div $2,$6
add $3,$2
mul $6,$3
mov $4,$6
equ $4,0
mov $0,$4
