; A267800: Triangle read by rows giving successive states of cellular automaton generated by "Rule 213" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,0,1,1,1,0,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1

mov $3,$0
add $0,1
lpb $3
  mov $3,1
  add $0,1
  mov $2,$0
  nrt $2,2
  add $2,1
  add $0,2
  mov $1,$0
  nrt $1,2
  mov $0,$1
  add $0,$2
lpe
mod $0,2
