; A267520: Triangle read by rows giving successive states of cellular automaton generated by "Rule 139" initiated with a single ON (black) cell.
; Submitted by loader3229
; 1,1,0,0,1,0,0,1,1,1,0,0,1,1,1,1,1,0,0,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1
; Formula: a(n) = ((-sqrtint(n)^2+n-1)!=1)*((sqrtint(n)^2)!=(n-1))

mov $1,$0
nrt $1,2
mov $2,$1
mul $2,$1
sub $0,1
pow $1,2
neq $1,$0
sub $0,$2
neq $0,1
mul $0,$1
