; A267778: Triangle read by rows giving successive states of cellular automaton generated by "Rule 211" initiated with a single ON (black) cell.
; Submitted by Athlici
; 1,1,0,1,1,1,0,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0

mov $2,1
sub $0,1
lpb $0
  add $2,2
  sub $0,$2
lpe
mov $1,$2
sub $1,1
bin $1,$0
sub $0,$1
bin $2,$0
mov $0,$2
add $0,1
mod $0,2
