; A267576: Triangle read by rows giving successive states of cellular automaton generated by "Rule 167" initiated with a single ON (black) cell.
; Submitted by Fardringle
; 1,1,1,0,1,1,0,1,0,1,1,0,1,1,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,1,1,1,1,1,1,0,1,1,0,1,0,1,1,1,1,1,0,1,0,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0

lpb $0
  sub $0,1
  sub $0,$1
  mov $2,$1
  add $1,2
lpe
bin $2,$0
bin $1,$0
sub $1,$2
mov $0,$1
add $0,1
mod $0,2
