; A267034: Triangle read by rows giving successive states of cellular automaton generated by "Rule 85" initiated with a single ON (black) cell.
; Submitted by fzs600
; 1,0,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
; Formula: a(n) = -2*truncate((d(n)+1)/2)+d(n)+1, b(n) = -b(n-1)+c(n-1)+truncate(b(n-1)/2), b(3) = 9, b(2) = 7, b(1) = 2, b(0) = 0, c(n) = gcd(truncate(b(n-1)/2),2)*(2*c(n-1)-2*b(n-1)+truncate(b(n-1)/2)), c(3) = 15, c(2) = 13, c(1) = 8, c(0) = 2, d(n) = d(n-1)+gcd(truncate(b(n-2)/2),2)+1, d(3) = 6, d(2) = 4, d(1) = 1, d(0) = 0

mov $2,2
lpb $0
  sub $0,1
  sub $2,$1
  add $4,1
  add $4,$3
  div $1,2
  mov $3,$1
  gcd $3,2
  add $1,$2
  add $2,$1
  mul $2,$3
lpe
mov $0,$4
add $0,1
mod $0,2
