; A267845: Triangle read by rows giving successive states of cellular automaton generated by "Rule 227" initiated with a single ON (black) cell.
; 1,1,0,0,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0

mov $6,$0
mov $4,4
lpb $4
  sub $4,1
  mov $3,0
  mov $0,$6
  add $0,$4
  sub $0,1
  lpb $0
    mov $2,$0
    add $3,1
    sub $0,1
    add $1,$5
    div $2,$3
    mov $5,8
    add $5,$2
  lpe
lpe
add $1,1
mod $1,2
mov $0,$1
