; A267810: Triangle read by rows giving successive states of cellular automaton generated by "Rule 217" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,0,0,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1

lpb $0
  add $1,1
  sub $0,$1
  sub $0,$1
lpe
pow $2,$0
mov $0,4
pow $0,$1
add $2,$0
mov $0,$2
add $0,1
mod $0,2
