; A267423: Triangle read by rows giving successive states of cellular automaton generated by "Rule 133" initiated with a single ON (black) cell.
; Submitted by USTL-FIL (Lille Fr)
; 1,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0

lpb $0
  seq $0,247644 ; Triangle formed from the odd-numbered rows of A088855.
  mul $0,2
  add $0,1
lpe
mov $2,$0
mul $0,2
mov $1,$0
add $1,$0
pow $2,$1
trn $0,$2
add $0,$1
div $0,4
add $0,1
mod $0,2
