; A267814: Triangle read by rows giving successive states of cellular automaton generated by "Rule 221" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1
; Formula: a(n) = sqrtint(4*n+6)==sqrtint(4*n+4)

mul $0,4
add $0,4
mov $2,$0
nrt $2,2
add $0,2
mov $1,$0
nrt $1,2
mov $0,$1
equ $0,$2
