; A267145: Triangle read by rows giving successive states of cellular automaton generated by "Rule 105" initiated with a single ON (black) cell.
; Submitted by Landjunge
; 1,0,0,0,1,0,1,0,1,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,1,0,0,0

mov $3,6
mov $5,3
lpb $0
  add $2,1
  add $6,1
  sub $0,$2
  add $2,1
lpe
mul $0,-1
add $0,$2
lpb $0
  sub $0,1
  add $3,$5
  add $4,1
  mov $1,$3
  mul $1,$2
  div $1,$4
  sub $2,2
  add $3,$1
  div $1,2
  mul $5,-1
  add $5,$1
  add $6,$5
lpe
mov $0,$6
add $0,1
mod $0,2
