; A267848: Triangle read by rows giving successive states of cellular automaton generated by "Rule 229" initiated with a single ON (black) cell.
; Submitted by Stony666
; 1,0,1,0,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0

mov $1,$0
add $0,2
mov $2,$0
mov $0,$1
lpb $2
  mod $2,6
  add $0,1
  seq $0,10052 ; Characteristic function of squares: a(n) = 1 if n is a square, otherwise 0.
lpe
add $0,1
mod $0,2
