; A267919: Triangle read by rows giving successive states of cellular automaton generated by "Rule 243" initiated with a single ON (black) cell.
; Submitted by Ralfy
; 1,1,0,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1
; Formula: a(n) = (b(n)+1)%2, b(n) = (b(n-1)/2-c(n-1))/2+c(n-1)*((b(n-1)/2-c(n-1)+d(n-1))%2+2), b(2) = 15, b(1) = 12, b(0) = 6, c(n) = (5*c(n-1))%(c(n-1)*((b(n-1)/2-c(n-1)+d(n-1))%2+2)), c(2) = 8, c(1) = 8, c(0) = 4, d(n) = c(n-1)*((b(n-1)/2-c(n-1)+d(n-1))%2+2), d(2) = 16, d(1) = 12, d(0) = 6

mov $2,2
add $0,2
lpb $0
  sub $0,1
  div $1,2
  sub $1,$2
  add $3,$1
  mod $3,2
  add $3,2
  mul $3,$2
  div $1,2
  add $1,$3
  mul $2,5
  mod $2,$3
lpe
mov $0,$1
add $0,1
mod $0,2
