; A267868: Triangle read by rows giving successive states of cellular automaton generated by "Rule 233" initiated with a single ON (black) cell.
; Submitted by Jamie Morken(s3)
; 1,0,0,0,1,0,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
; Formula: a(n) = (((2*n)^2+2)/(2*gcd(gcd(-n,2)+1,2*n)+2*n)+1)%2

sub $1,$0
mul $0,2
gcd $1,2
add $1,1
gcd $1,$0
mul $1,2
add $1,$0
pow $0,2
add $0,2
div $0,$1
add $0,1
mod $0,2
