; A267848: Triangle read by rows giving successive states of cellular automaton generated by "Rule 229" initiated with a single ON (black) cell.
; Submitted by loader3229
; 1,0,1,0,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
; Formula: a(n) = (sqrtint(n+1)^2)!=min(n+1,binomial(n+1,2))

add $0,1
mov $1,$0
bin $1,2
mov $2,$0
min $0,$1
nrt $2,2
pow $2,2
neq $2,$0
mov $0,$2
