; A267676: Triangle read by rows giving successive states of cellular automaton generated by "Rule 197" initiated with a single ON (black) cell.
; Submitted by trigggl
; 1,0,1,0,1,0,1,0,0,1,1,0,1,0,0,0,1,1,1,0,1,0,1,0,0,1,1,1,1,0,1,0,1,0,0,0,1,1,1,1,1,0,1,0,1,0,1,0,0,1,1,1,1,1,1,0,1,0,1,0,1,0,0,0,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,0,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,0,0

add $0,1
mov $2,$0
lpb $0
  add $1,1
  min $0,$1
  mov $3,$2
  dif $3,$0
  mul $0,2
  sub $0,1
  max $0,$3
  cmp $3,$2
  mul $3,$0
  sub $2,$1
  mov $0,$2
  sub $2,$1
lpe
mov $0,$3
mod $0,2
