; A267814: Triangle read by rows giving successive states of cellular automaton generated by "Rule 221" initiated with a single ON (black) cell.
; Submitted by Josemi
; 1,0,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1

add $0,1
mov $3,$0
mul $3,4
mov $1,$3
nrt $1,2
mul $0,2
add $0,1
mul $0,2
mov $2,$0
nrt $2,2
mov $0,$2
mod $0,2
mov $3,$1
pow $3,$0
mov $0,$3
mod $0,2
