; A267927: Triangle read by rows giving successive states of cellular automaton generated by "Rule 249" initiated with a single ON (black) cell.
; Submitted by Saj
; 1,0,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
; Formula: a(n) = e(n)+1, b(n) = c(n-1), b(8) = 1, b(7) = 1, b(6) = 1, b(5) = 0, b(4) = 1, b(3) = 1, b(2) = 1, b(1) = 0, b(0) = 0, c(n) = if((d(n-2)^2)==1,d(n-2)^d(n-1),if(d(n-1)<=(-1),0,d(n-2)^d(n-1))), c(8) = 1, c(7) = 1, c(6) = 1, c(5) = 1, c(4) = 0, c(3) = 1, c(2) = 1, c(1) = 1, c(0) = 0, d(n) = truncate((c(n-5)+c(n-6))/8), d(9) = 0, d(8) = 0, d(7) = 0, d(6) = 0, d(5) = 0, d(4) = 1, d(3) = 1, d(2) = 0, d(1) = 0, d(0) = 0, e(n) = b(n-1)-1, e(8) = 0, e(7) = 0, e(6) = -1, e(5) = 0, e(4) = 0, e(3) = 0, e(2) = -1, e(1) = -1, e(0) = 0

mov $8,15
lpb $0
  sub $0,1
  pow $3,$4
  add $7,$8
  mov $9,$1
  sub $9,1
  rol $1,8
  div $4,8
lpe
mov $0,$9
add $0,1
