; A267810: Triangle read by rows giving successive states of cellular automaton generated by "Rule 217" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,0,0,1,1,1,0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1
; Formula: a(n) = 0^binomial(n,2)-sqrtint(4*n)-sqrtint(4*n+2)-2*truncate((0^binomial(n,2)-sqrtint(4*n)-sqrtint(4*n+2))/2)+1

mov $2,$0
mul $2,4
mov $4,$2
nrt $4,2
mov $1,$0
mul $1,2
add $1,1
mul $1,2
mov $3,$1
nrt $3,2
add $4,$3
bin $0,2
pow $5,$0
mov $0,$5
sub $0,$4
mod $0,2
add $0,1
