; A267598: Triangle read by rows giving successive states of cellular automaton generated by "Rule 177" initiated with a single ON (black) cell.
; Submitted by Science United
; 1,0,0,1,0,1,0,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0

max $2,$0
add $2,2
mov $3,$2
mul $3,4
lpb $2
  mov $1,$3
  div $1,$2
  add $2,$1
  div $2,2
lpe
div $2,2
add $0,$2
mod $0,2
