; A178931: This sequence S is generated by the following rules: 2 is in S, and if n is in S, then floor[(3n-1)/2] and 3n are in S.
; Submitted by Jamie Morken(l1)
; 2,6,8,11,16,18,23,24,26,33,34,35,38,48,49,50,52,54,56,69,71,72,73,74,77,78,80,83,99,102,103,105,106,107,109,110,114,115,116,119,124,144,147,148,150,152,154,156,157,158,160,162,163,164,168,170,172,173,178,185,207,213,215,216,219,220,221,222,224,227,230,231,233,234,235,236,239,240,242,244,245,249,251,254,257,259,266,277,297,306,309,310,315,318,319,321,322,323,327,328

mov $2,$0
add $2,2
pow $2,2
lpb $2
  add $1,1
  mov $3,$1
  seq $3,117943 ; a(1) = 0, a(2) = 1; a(3n) = a(n); if every third term (a(3), a(6), a(9), ...) is deleted, this gives back the original sequence.
  sub $0,$3
  mov $4,$0
  max $4,0
  cmp $4,$0
  mul $2,$4
  sub $2,1
lpe
mov $0,$1
add $0,2
