; A301848: Number of states generated by morphism during inflation stage of paper-folding sequence.
; 1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,2,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,2,3,1,4,1

mov $2,$0
cal $0,38189 ; Bit to left of least significant 1-bit in binary expansion of n.
sub $0,2
mov $1,$0
add $1,7
div $1,2
mod $2,2
mul $2,2
add $1,$2
sub $1,1
