; A301848: Number of states generated by morphism during inflation stage of paper-folding sequence.
; 1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,2,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,1,3,1,4,2,3,2,4,1,3,1,4,1,3,2,4,2,3,1,4,2,3,2,4,2,3,1,4

mov $2,$0
seq $0,38189 ; Bit to left of least significant 1-bit in binary expansion of n.
add $0,5
div $0,2
mod $2,2
mul $2,2
add $0,$2
sub $0,1
