; A354499: Number of consecutive primes generated by adding 2n to the odd squares (A016754).
; Submitted by USTL-FIL (Lille Fr)
; 2,4,1,0,2,1,0,1,1,0,5,0,0,3,1,0,0,1,0,1,1,0,1,0,0,2,0,0,14,1,0,0,1,0,2,1,0,0,1,0,1,0,0,4,0,0,0,1,0,2,1,0,1,1,0,1,0,0,0,0,0,0,1,0,2,0,0,1,1,0,0,0,0,8,1,0,0,1,0,0,1,0,1,0,0,3,0,0,1,1,0,0,0,0,2,1,0,1,1,0

mov $2,$0
add $0,1
mov $4,$0
add $2,5
lpb $2
  max $3,$4
  mul $3,2
  seq $3,5171 ; Characteristic function of nonprimes: 0 if n is prime, else 1.
  mov $0,1
  sub $0,$3
  add $1,4
  sub $2,$0
  add $4,$1
lpe
mov $0,$1
div $0,4
