; A121946: Let r be the matrix {{1,1},{0,1}} and b={{1,0},{1,0}}. Let A be the semigroup generated by r and b. a(n) is the number of words of length n in A.
; Submitted by ChelseaOilman
; 1,2,3,5,8,12,18,26,37,51,69,92,121,157,202,257,324,405,503,620,760,926,1122,1353,1624,1941,2310,2739,3235,3808,4468,5226,6095,7088,8221,9511,10976,12638,14519,16644,19041

lpb $0
  sub $0,1
  mov $2,$0
  max $2,0
  seq $2,34891 ; Number of different products of partitions of n; number of partitions of n into prime parts (1 included); number of distinct orders of Abelian subgroups of symmetric group S_n.
  add $1,$2
lpe
add $1,1
mov $0,$1
