name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-programs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: ls
      - name: Check
        run: ./check_merge.sh
