; A127243: Triangle whose k-th column is generated by (1+A010060(1+k)x)*x^k.
; Submitted by fzs600
; 1,1,1,0,1,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0
; Formula: a(n) = sumdigits(binomial(-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1,binomial(truncate((sqrtint(8*n+8)-1)/2),-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1)),2)*sign(binomial(-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1,binomial(truncate((sqrtint(8*n+8)-1)/2),-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1)))-2*truncate((sumdigits(binomial(-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1,binomial(truncate((sqrtint(8*n+8)-1)/2),-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1)),2)*sign(binomial(-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1,binomial(truncate((sqrtint(8*n+8)-1)/2),-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1))))/2)

add $0,1
mov $2,$0
mul $2,8
nrt $2,2
sub $2,1
div $2,2
mov $1,$2
add $1,1
bin $1,2
sub $0,$1
bin $2,$0
bin $0,$2
dgs $0,2
mod $0,2
