; A127248: Triangle whose k-th column is generated by (1-A010060(1+k)*x)*x^k.
; Submitted by Ari
; 1,-1,1,0,-1,1,0,0,0,1,0,0,0,-1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,-1,1,0,0,0,0,0,0,0,-1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,-1,1,0,0
; Formula: a(n) = truncate((-1)^(-n+truncate((sqrtint(8*n+8)-1)/4)))*(sumdigits(binomial(-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1,binomial(truncate((sqrtint(8*n+8)-1)/2),-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1)),2)*sign(binomial(-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1,binomial(truncate((sqrtint(8*n+8)-1)/2),-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1)))-2*truncate((sumdigits(binomial(-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1,binomial(truncate((sqrtint(8*n+8)-1)/2),-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1)),2)*sign(binomial(-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1,binomial(truncate((sqrtint(8*n+8)-1)/2),-binomial(truncate((sqrtint(8*n+8)-1)/2)+1,2)+n+1))))/2))

mov $1,$0
add $1,1
mov $4,$1
mul $4,8
nrt $4,2
sub $4,1
div $4,2
mov $5,$4
add $5,1
bin $5,2
add $0,1
sub $1,$5
bin $4,$1
bin $1,$4
dgs $1,2
mod $1,2
mov $3,$0
mul $3,8
nrt $3,2
sub $3,1
div $3,4
sub $0,1
sub $3,$0
mov $2,-1
pow $2,$3
mov $0,$2
mul $0,$1
