; A127248: Triangle whose k-th column is generated by (1-A010060(1+k)*x)*x^k.
; Submitted by Fornax
; 1,-1,1,0,-1,1,0,0,0,1,0,0,0,-1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,-1,1,0,0,0,0,0,0,0,-1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,-1,1,0,0
; Formula: a(n) = A097807(n)*A010060(A128229(n+1))

mov $1,$0
add $1,1
seq $1,128229 ; A natural number transform, inverse of signed A094587.
seq $1,10060 ; Thue-Morse sequence: let A_k denote the first 2^k terms; then A_0 = 0 and for k >= 0, A_{k+1} = A_k B_k, where B_k is obtained from A_k by interchanging 0's and 1's.
seq $0,97807 ; Riordan array (1/(1+x),1) read by rows.
mul $0,$1
