; A033042: Sums of distinct powers of 5.
; 0,1,5,6,25,26,30,31,125,126,130,131,150,151,155,156,625,626,630,631,650,651,655,656,750,751,755,756,775,776,780,781,3125,3126,3130,3131,3150,3151,3155,3156,3250,3251,3255,3256,3275,3276,3280,3281,3750,3751

cal $0,191107 ; Increasing sequence generated by these rules:  a(1)=1, and if x is in a then 3x-2 and 3x+1 are in a.
cal $0,37453 ; Positive numbers n such that the base 5 representation of n contains no 3 or 4.
mov $1,$0
div $1,5
