; A232559: Sequence (or tree) generated by these rules: 1 is in S, and if x is in S, then x + 1 and 2*x are in S, and duplicates are deleted as they occur.
; Submitted by Science United
; 1,2,3,4,6,5,8,7,12,10,9,16,14,13,24,11,20,18,17,32,15,28,26,25,48,22,21,40,19,36,34,33,64,30,29,56,27,52,50,49,96,23,44,42,41,80,38,37,72,35,68,66,65,128,31,60,58,57,112,54,53,104,51,100,98,97,192,46,45,88,43,84,82,81,160,39,76,74,73,144
; Formula: a(n) = truncate((A345401(A348366(n))-5)/2)+2

#offset 1

seq $0,348366 ; a(n) = 2*a(n - A130312(n)) + (A072649(n) - A072649(n - A130312(n))) mod 2 for n > 1 with a(0) = 0, a(1) = 1.
seq $0,345401 ; a(n) is the unique odd number h such that BCR(h*2^m-1) = 2n (except for BCR(0) = 1) where BCR is bit complement and reverse per A036044.
sub $0,5
div $0,2
add $0,2
