; A232638: Sequence (or tree) generated by these rules: 1 is in S, and if x is in S, then x + 1 and 2*x - 1 are in S, and duplicates are deleted as they occur.
; Submitted by fzs600
; 1,2,3,4,5,7,6,9,8,13,11,10,17,15,14,25,12,21,19,18,33,16,29,27,26,49,23,22,41,20,37,35,34,65,31,30,57,28,53,51,50,97,24,45,43,42,81,39,38,73,36,69,67,66,129,32,61,59,58,113,55,54,105,52,101,99,98,193,47,46,89,44,85,83,82,161,40,77,75,74,145,71,70,137,68,133,131,130,257,63,62,121,60,117,115,114,225,56,109,107
; Formula: a(n) = A345401(A348366(n))/2+1

seq $0,348366 ; Permutation of natural numbers such that A284005(a(n)) = A347188(n+1) for n >= 0.
seq $0,345401 ; a(n) is the unique odd number h such that BCR(h*2^m-1) = 2n (except for BCR(0) = 1) where BCR is bit complement and reverse per A036044.
div $0,2
add $0,1
