; A232640: Sequence (or tree) generated by these rules: 1 is in S, and if x is in S, then x + 1 and 2*x + 1 are in S, and duplicates are deleted as they occur.
; Submitted by Egon Olsen
; 1,2,3,5,4,7,6,11,9,8,15,13,12,23,10,19,17,16,31,14,27,25,24,47,21,20,39,18,35,33,32,63,29,28,55,26,51,49,48,95,22,43,41,40,79,37,36,71,34,67,65,64,127,30,59,57,56,111,53,52,103,50,99,97,96,191,45,44,87,42,83,81,80,159,38,75,73,72,143,69,68,135,66,131,129,128,255,61,60,119,58,115,113,112,223,54,107,105,104,207
; Formula: a(n) = (A345401(A348366(n+2))-5)/2+1

add $0,2
seq $0,348366 ; Permutation of natural numbers such that A284005(a(n)) = A347188(n+1) for n >= 0.
seq $0,345401 ; a(n) is the unique odd number h such that BCR(h*2^m-1) = 2n (except for BCR(0) = 1) where BCR is bit complement and reverse per A036044.
sub $0,5
div $0,2
add $0,1
