; A232646: Sequence (or tree or triangle) generated by these rules: 1 is in S, and if x is in S, then 2*x and 5*x + 3 are in S, and duplicates are deleted as they occur.
; Submitted by loader3229
; 1,2,5,4,10,25,8,20,50,125,16,40,100,250,625,32,80,200,500,1250,3125,64,160,400,1000,2500,6250,15625,128,320,800,2000,5000,12500,31250,78125,256,640,1600,4000,10000,25000,62500,156250,390625,512,1280,3200,8000,20000,50000,125000,312500,781250,1953125,1024,2560,6400,16000,40000,100000,250000,625000,1562500,3906250,9765625,2048,5120,12800,32000,80000,200000,500000,1250000,3125000,7812500,19531250,48828125,4096,10240
; Formula: a(n) = truncate(2^(-n+binomial(truncate((sqrtint(8*n)-1)/2)+1,2)+truncate((sqrtint(8*n)-1)/2)+1))*truncate(5^(-binomial(truncate((sqrtint(8*n)-1)/2)+1,2)+n-1))

#offset 1

mov $1,$0
mul $1,8
nrt $1,2
sub $1,1
div $1,2
mov $3,$1
add $3,1
bin $3,2
sub $0,$3
sub $0,1
sub $1,$0
mov $2,5
pow $2,$0
mov $0,$2
mov $2,2
pow $2,$1
mul $2,$0
mov $0,$2
