; A232642: Sequence (or tree) generated by these rules: 1 is in S, and if x is in S, then x + 1 and 2*x + 2 are in S, and duplicates are deleted as they occur.
; Submitted by Egon Olsen
; 1,2,4,3,6,5,10,8,7,14,12,11,22,9,18,16,15,30,13,26,24,23,46,20,19,38,17,34,32,31,62,28,27,54,25,50,48,47,94,21,42,40,39,78,36,35,70,33,66,64,63,126,29,58,56,55,110,52,51,102,49,98,96,95,190,44,43,86,41,82,80,79,158,37,74,72,71,142,68,67,134,65,130,128,127,254,60,59,118,57,114,112,111,222,53,106,104,103,206,100
; Formula: a(n) = (A345401(A348366(n+3))-5)/2

add $0,3
seq $0,348366 ; Permutation of natural numbers such that A284005(a(n)) = A347188(n+1) for n >= 0.
seq $0,345401 ; a(n) is the unique odd number h such that BCR(h*2^m-1) = 2n (except for BCR(0) = 1) where BCR is bit complement and reverse per A036044.
sub $0,5
div $0,2
