; A232866: Positions of the nonnegative integers in the sequence (or tree) of complex numbers generated by these rules: 0 is in S, and if x is in S, then x + 1 and i*x are in S, where duplicates are deleted as they occur.
; Submitted by BrandyNOW
; 1,2,3,5,9,16,27,42,61,84,111,142,177,216,259,306,357,412,471,534,601,672,747,826,909,996,1087,1182,1281,1384,1491,1602,1717,1836,1959,2086,2217,2352,2491,2634,2781,2932,3087,3246,3409,3576,3747,3922,4101,4284,4471,4662,4857,5056,5259,5466,5677,5892,6111,6334,6561,6792,7027,7266,7509,7756,8007,8262,8521,8784,9051,9322,9597,9876,10159,10446,10737,11032,11331,11634
; Formula: a(n) = b(n-1), b(n) = 2*b(n-1)-b(n-2)+min(b(n-3),4), b(6) = 27, b(5) = 16, b(4) = 9, b(3) = 5, b(2) = 3, b(1) = 2, b(0) = 1

#offset 1

mov $1,1
mov $4,1
sub $0,1
lpb $0
  sub $0,1
  add $2,$1
  mov $1,$3
  min $1,4
  mov $3,$4
  add $4,$2
lpe
mov $0,$4
