; A232868: Positions of the integers in the sequence (or tree) of complex numbers generated by these rules: 0 is in S, and if x is in S, then x + 1 and i*x are in S, where duplicates are deleted as they occur.
; Submitted by loader3229
; 1,2,3,5,8,9,12,16,19,27,30,42,45,61,64,84,87,111,114,142,145,177,180,216,219,259,262,306,309,357,360,412,415,471,474,534,537,601,604,672,675,747,750,826,829,909,912,996,999,1087,1090,1182,1185,1281,1284

#offset 1

mov $1,1
mov $2,2
mov $3,3
mov $4,5
mov $5,8
mov $6,9
mov $7,12
mov $8,16
mov $9,19
mov $10,27
sub $0,1
lpb $0
  mul $1,0
  rol $1,10
  add $10,$5
  sub $10,$6
  sub $10,$7
  sub $10,$7
  add $10,$8
  add $10,$8
  add $10,$9
  sub $0,1
lpe
mov $0,$1
